// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class AccountDocumentShowResponseDto {

  /**
   * Reason why account approval was rejected
   */
  @JsonProperty("rejectReasons")
  private JsonNullable<String> rejectReasons;

  /**
   * List of objects
   */
  @JsonProperty("data")
  private JsonNullable<List<AccountDocumentGroupResponseDto>> data;

  @JsonIgnore
  public String getRejectReasons() {
    return rejectReasons.orElse(null);
  }

  @JsonIgnore
  public List<AccountDocumentGroupResponseDto> getData() {
    return data.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class AccountDocumentShowResponseDtoBuilder {

    private JsonNullable<String> rejectReasons = JsonNullable.undefined();

    @JsonProperty("rejectReasons")
    public AccountDocumentShowResponseDtoBuilder rejectReasons(String value) {
      this.rejectReasons = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<List<AccountDocumentGroupResponseDto>> data = JsonNullable.undefined();

    @JsonProperty("data")
    public AccountDocumentShowResponseDtoBuilder data(List<AccountDocumentGroupResponseDto> value) {
      this.data = JsonNullable.of(value);
      return this;
    }
  }
}
