// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Anticipation status
 */
@Getter
@AllArgsConstructor
public enum AnticipationGetResponseAnticipationStatus {
  PENDING("PENDING"),
  DENIED("DENIED"),
  CREDITED("CREDITED"),
  DEBITED("DEBITED"),
  CANCELLED("CANCELLED"),
  OVERDUE("OVERDUE"),
  SCHEDULED("SCHEDULED");

  @JsonValue
  private final String value;

  @JsonCreator
  public static AnticipationGetResponseAnticipationStatus fromValue(String value) {
    return Arrays.stream(AnticipationGetResponseAnticipationStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
