// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiBillGetResponseDto {

  /**
   * Object type
   */
  @JsonProperty("object")
  private JsonNullable<String> object;

  /**
   * Unique bill payment identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Bill payment status
   */
  @JsonProperty("status")
  private JsonNullable<ApiBillGetResponseBillStatus> status;

  /**
   * Amount to be paid
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Discount attributed to payment
   */
  @JsonProperty("discount")
  private JsonNullable<Double> discount;

  /**
   * Interest attributed to payment
   */
  @JsonProperty("interest")
  private JsonNullable<Double> interest;

  /**
   * Fine assigned to payment
   */
  @JsonProperty("fine")
  private JsonNullable<Double> fine;

  /**
   * Typeable line of the bill to be paid
   */
  @JsonProperty("identificationField")
  private JsonNullable<String> identificationField;

  /**
   * Billing due date
   */
  @JsonProperty("dueDate")
  private JsonNullable<String> dueDate;

  /**
   * Payment scheduling date
   */
  @JsonProperty("scheduleDate")
  private JsonNullable<String> scheduleDate;

  /**
   * Date on which payment was made
   */
  @JsonProperty("paymentDate")
  private JsonNullable<String> paymentDate;

  /**
   * Asaas fee for bill payment
   */
  @JsonProperty("fee")
  private JsonNullable<Double> fee;

  /**
   * Bill Payment Description
   */
  @JsonProperty("description")
  private JsonNullable<String> description;

  /**
   * Company/Body issuing the payment
   */
  @JsonProperty("companyName")
  private JsonNullable<String> companyName;

  /**
   * Proof of bill payment
   */
  @JsonProperty("transactionReceiptUrl")
  private JsonNullable<String> transactionReceiptUrl;

  /**
   * Whether payment can be canceled
   */
  @JsonProperty("canBeCancelled")
  private JsonNullable<Boolean> canBeCancelled;

  /**
   * Unique identifier of the bill in your system
   */
  @JsonProperty("externalReference")
  private JsonNullable<String> externalReference;

  /**
   * List of reasons for payment failure
   */
  @JsonProperty("failReasons")
  private JsonNullable<List<String>> failReasons;

  @JsonIgnore
  public String getObject() {
    return object.orElse(null);
  }

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public ApiBillGetResponseBillStatus getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public Double getDiscount() {
    return discount.orElse(null);
  }

  @JsonIgnore
  public Double getInterest() {
    return interest.orElse(null);
  }

  @JsonIgnore
  public Double getFine() {
    return fine.orElse(null);
  }

  @JsonIgnore
  public String getIdentificationField() {
    return identificationField.orElse(null);
  }

  @JsonIgnore
  public String getDueDate() {
    return dueDate.orElse(null);
  }

  @JsonIgnore
  public String getScheduleDate() {
    return scheduleDate.orElse(null);
  }

  @JsonIgnore
  public String getPaymentDate() {
    return paymentDate.orElse(null);
  }

  @JsonIgnore
  public Double getFee() {
    return fee.orElse(null);
  }

  @JsonIgnore
  public String getDescription() {
    return description.orElse(null);
  }

  @JsonIgnore
  public String getCompanyName() {
    return companyName.orElse(null);
  }

  @JsonIgnore
  public String getTransactionReceiptUrl() {
    return transactionReceiptUrl.orElse(null);
  }

  @JsonIgnore
  public Boolean getCanBeCancelled() {
    return canBeCancelled.orElse(null);
  }

  @JsonIgnore
  public String getExternalReference() {
    return externalReference.orElse(null);
  }

  @JsonIgnore
  public List<String> getFailReasons() {
    return failReasons.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiBillGetResponseDtoBuilder {

    private JsonNullable<String> object = JsonNullable.undefined();

    @JsonProperty("object")
    public ApiBillGetResponseDtoBuilder object(String value) {
      this.object = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public ApiBillGetResponseDtoBuilder id(String value) {
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiBillGetResponseBillStatus> status = JsonNullable.undefined();

    @JsonProperty("status")
    public ApiBillGetResponseDtoBuilder status(ApiBillGetResponseBillStatus value) {
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public ApiBillGetResponseDtoBuilder value(Double value) {
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> discount = JsonNullable.undefined();

    @JsonProperty("discount")
    public ApiBillGetResponseDtoBuilder discount(Double value) {
      this.discount = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> interest = JsonNullable.undefined();

    @JsonProperty("interest")
    public ApiBillGetResponseDtoBuilder interest(Double value) {
      this.interest = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> fine = JsonNullable.undefined();

    @JsonProperty("fine")
    public ApiBillGetResponseDtoBuilder fine(Double value) {
      this.fine = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> identificationField = JsonNullable.undefined();

    @JsonProperty("identificationField")
    public ApiBillGetResponseDtoBuilder identificationField(String value) {
      this.identificationField = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dueDate = JsonNullable.undefined();

    @JsonProperty("dueDate")
    public ApiBillGetResponseDtoBuilder dueDate(String value) {
      this.dueDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> scheduleDate = JsonNullable.undefined();

    @JsonProperty("scheduleDate")
    public ApiBillGetResponseDtoBuilder scheduleDate(String value) {
      this.scheduleDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> paymentDate = JsonNullable.undefined();

    @JsonProperty("paymentDate")
    public ApiBillGetResponseDtoBuilder paymentDate(String value) {
      this.paymentDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> fee = JsonNullable.undefined();

    @JsonProperty("fee")
    public ApiBillGetResponseDtoBuilder fee(Double value) {
      this.fee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> description = JsonNullable.undefined();

    @JsonProperty("description")
    public ApiBillGetResponseDtoBuilder description(String value) {
      this.description = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> companyName = JsonNullable.undefined();

    @JsonProperty("companyName")
    public ApiBillGetResponseDtoBuilder companyName(String value) {
      this.companyName = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> transactionReceiptUrl = JsonNullable.undefined();

    @JsonProperty("transactionReceiptUrl")
    public ApiBillGetResponseDtoBuilder transactionReceiptUrl(String value) {
      this.transactionReceiptUrl = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> canBeCancelled = JsonNullable.undefined();

    @JsonProperty("canBeCancelled")
    public ApiBillGetResponseDtoBuilder canBeCancelled(Boolean value) {
      this.canBeCancelled = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> externalReference = JsonNullable.undefined();

    @JsonProperty("externalReference")
    public ApiBillGetResponseDtoBuilder externalReference(String value) {
      this.externalReference = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<List<String>> failReasons = JsonNullable.undefined();

    @JsonProperty("failReasons")
    public ApiBillGetResponseDtoBuilder failReasons(List<String> value) {
      this.failReasons = JsonNullable.of(value);
      return this;
    }
  }
}
