// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiBillSimulateResponseDto {

  /**
   * Minimum date allowed for scheduling
   */
  @JsonProperty("minimumScheduleDate")
  private JsonNullable<String> minimumScheduleDate;

  /**
   * Fee charged when paying the bill
   */
  @JsonProperty("fee")
  private JsonNullable<Double> fee;

  @JsonProperty("bankSlipInfo")
  private JsonNullable<ApiBillSimulateBankSlipInfoResponseDto> bankSlipInfo;

  @JsonIgnore
  public String getMinimumScheduleDate() {
    return minimumScheduleDate.orElse(null);
  }

  @JsonIgnore
  public Double getFee() {
    return fee.orElse(null);
  }

  @JsonIgnore
  public ApiBillSimulateBankSlipInfoResponseDto getBankSlipInfo() {
    return bankSlipInfo.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiBillSimulateResponseDtoBuilder {

    private JsonNullable<String> minimumScheduleDate = JsonNullable.undefined();

    @JsonProperty("minimumScheduleDate")
    public ApiBillSimulateResponseDtoBuilder minimumScheduleDate(String value) {
      if (value == null) {
        throw new IllegalStateException("minimumScheduleDate cannot be null");
      }
      this.minimumScheduleDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> fee = JsonNullable.undefined();

    @JsonProperty("fee")
    public ApiBillSimulateResponseDtoBuilder fee(Double value) {
      if (value == null) {
        throw new IllegalStateException("fee cannot be null");
      }
      this.fee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiBillSimulateBankSlipInfoResponseDto> bankSlipInfo = JsonNullable.undefined();

    @JsonProperty("bankSlipInfo")
    public ApiBillSimulateResponseDtoBuilder bankSlipInfo(ApiBillSimulateBankSlipInfoResponseDto value) {
      if (value == null) {
        throw new IllegalStateException("bankSlipInfo cannot be null");
      }
      this.bankSlipInfo = JsonNullable.of(value);
      return this;
    }
  }
}
