// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCheckoutSessionSplitDto {

  /**
   * Asaas wallet identifier that will receive the transfer
   */
  @NonNull
  private String walletId;

  /**
   * Fixed amount to be transferred to the account when the payment is received
   */
  @JsonProperty("fixedValue")
  private JsonNullable<Double> fixedValue;

  /**
   * Percentage of the net value of the charge to be transferred when received
   */
  @JsonProperty("percentageValue")
  private JsonNullable<Double> percentageValue;

  /**
   * (Instalments only). Amount that will be split relative to the total amount that will be paid in installments.
   */
  @JsonProperty("totalFixedValue")
  private JsonNullable<Double> totalFixedValue;

  @JsonIgnore
  public Double getFixedValue() {
    return fixedValue.orElse(null);
  }

  @JsonIgnore
  public Double getPercentageValue() {
    return percentageValue.orElse(null);
  }

  @JsonIgnore
  public Double getTotalFixedValue() {
    return totalFixedValue.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiCheckoutSessionSplitDtoBuilder {

    private JsonNullable<Double> fixedValue = JsonNullable.undefined();

    @JsonProperty("fixedValue")
    public ApiCheckoutSessionSplitDtoBuilder fixedValue(Double value) {
      this.fixedValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> percentageValue = JsonNullable.undefined();

    @JsonProperty("percentageValue")
    public ApiCheckoutSessionSplitDtoBuilder percentageValue(Double value) {
      this.percentageValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> totalFixedValue = JsonNullable.undefined();

    @JsonProperty("totalFixedValue")
    public ApiCheckoutSessionSplitDtoBuilder totalFixedValue(Double value) {
      this.totalFixedValue = JsonNullable.of(value);
      return this;
    }
  }
}
