// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCreditBureauReportSaveRequestDto {

  /**
   * Unique customer identifier in Asaas
   */
  @JsonProperty("customer")
  private JsonNullable<String> customer;

  /**
   * CPF or CNPJ of the customer. Enter this field if your client is not registered with Asaas
   */
  @JsonProperty("cpfCnpj")
  private JsonNullable<String> cpfCnpj;

  @JsonIgnore
  public String getCustomer() {
    return customer.orElse(null);
  }

  @JsonIgnore
  public String getCpfCnpj() {
    return cpfCnpj.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiCreditBureauReportSaveRequestDtoBuilder {

    private JsonNullable<String> customer = JsonNullable.undefined();

    @JsonProperty("customer")
    public ApiCreditBureauReportSaveRequestDtoBuilder customer(String value) {
      this.customer = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> cpfCnpj = JsonNullable.undefined();

    @JsonProperty("cpfCnpj")
    public ApiCreditBureauReportSaveRequestDtoBuilder cpfCnpj(String value) {
      this.cpfCnpj = JsonNullable.of(value);
      return this;
    }
  }
}
