// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCreditCardTokenizeRequestDto {

  /**
   * Unique customer identifier in Asaas
   */
  @NonNull
  private String customer;

  @JsonInclude(JsonInclude.Include.ALWAYS)
  private ApiCreditCardRequestDto creditCard;

  @JsonInclude(JsonInclude.Include.ALWAYS)
  private ApiCreditCardHolderInfoRequestDto creditCardHolderInfo;

  /**
   * IP from where the customer is making the purchase. Your server's IP must not be entered.
   */
  @NonNull
  private String remoteIp;

  // Overwrite lombok builder methods
  public static class ApiCreditCardTokenizeRequestDtoBuilder {

    /**
     * Flag to track if the creditCard property has been set.
     */
    private boolean creditCard$set = false;

    /**
     * Flag to track if the creditCardHolderInfo property has been set.
     */
    private boolean creditCardHolderInfo$set = false;

    public ApiCreditCardTokenizeRequestDtoBuilder creditCard(ApiCreditCardRequestDto creditCard) {
      this.creditCard$set = true;
      this.creditCard = creditCard;
      return this;
    }

    public ApiCreditCardTokenizeRequestDtoBuilder creditCardHolderInfo(
      ApiCreditCardHolderInfoRequestDto creditCardHolderInfo
    ) {
      this.creditCardHolderInfo$set = true;
      this.creditCardHolderInfo = creditCardHolderInfo;
      return this;
    }

    public ApiCreditCardTokenizeRequestDto build() {
      if (!creditCard$set) {
        throw new IllegalStateException("creditCard is required");
      }
      if (!creditCardHolderInfo$set) {
        throw new IllegalStateException("creditCardHolderInfo is required");
      }
      return new ApiCreditCardTokenizeRequestDto(customer, creditCard, creditCardHolderInfo, remoteIp);
    }
  }
}
