// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * State abbreviation (SP, RJ, SC, ...)
 */
@Getter
@AllArgsConstructor
public enum ApiCustomerUpdateRequestCityState {
  AC("AC"),
  AL("AL"),
  AP("AP"),
  AM("AM"),
  BA("BA"),
  CE("CE"),
  DF("DF"),
  ES("ES"),
  GO("GO"),
  MA("MA"),
  MT("MT"),
  MS("MS"),
  MG("MG"),
  PA("PA"),
  PB("PB"),
  PR("PR"),
  PE("PE"),
  PI("PI"),
  RR("RR"),
  RO("RO"),
  RJ("RJ"),
  RN("RN"),
  RS("RS"),
  SC("SC"),
  SP("SP"),
  SE("SE"),
  TO("TO");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiCustomerUpdateRequestCityState fromValue(String value) {
    return Arrays.stream(ApiCustomerUpdateRequestCityState.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
