// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiInstallmentUpdateSplitResponseDto {

  /**
   * Split array
   */
  @JsonProperty("splits")
  private JsonNullable<List<ApiInstallmentSplitGetResponseDto>> splits;

  @JsonIgnore
  public List<ApiInstallmentSplitGetResponseDto> getSplits() {
    return splits.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiInstallmentUpdateSplitResponseDtoBuilder {

    private JsonNullable<List<ApiInstallmentSplitGetResponseDto>> splits = JsonNullable.undefined();

    @JsonProperty("splits")
    public ApiInstallmentUpdateSplitResponseDtoBuilder splits(List<ApiInstallmentSplitGetResponseDto> value) {
      this.splits = JsonNullable.of(value);
      return this;
    }
  }
}
