// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiMyAccountGetAccountFeesPaymentDebitCardDto {

  /**
   * Operating fee per charge
   */
  @JsonProperty("operationValue")
  private JsonNullable<Double> operationValue;

  /**
   * Percentage rate per charge
   */
  @JsonProperty("defaultPercentage")
  private JsonNullable<Double> defaultPercentage;

  /**
   * Days to receive billing
   */
  @JsonProperty("daysToReceive")
  private JsonNullable<Long> daysToReceive;

  @JsonIgnore
  public Double getOperationValue() {
    return operationValue.orElse(null);
  }

  @JsonIgnore
  public Double getDefaultPercentage() {
    return defaultPercentage.orElse(null);
  }

  @JsonIgnore
  public Long getDaysToReceive() {
    return daysToReceive.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiMyAccountGetAccountFeesPaymentDebitCardDtoBuilder {

    private JsonNullable<Double> operationValue = JsonNullable.undefined();

    @JsonProperty("operationValue")
    public ApiMyAccountGetAccountFeesPaymentDebitCardDtoBuilder operationValue(Double value) {
      this.operationValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> defaultPercentage = JsonNullable.undefined();

    @JsonProperty("defaultPercentage")
    public ApiMyAccountGetAccountFeesPaymentDebitCardDtoBuilder defaultPercentage(Double value) {
      this.defaultPercentage = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> daysToReceive = JsonNullable.undefined();

    @JsonProperty("daysToReceive")
    public ApiMyAccountGetAccountFeesPaymentDebitCardDtoBuilder daysToReceive(Long value) {
      this.daysToReceive = JsonNullable.of(value);
      return this;
    }
  }
}
