// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiMyAccountGetAccountFeesAnticipationDto {

  @JsonProperty("creditCard")
  private JsonNullable<ApiMyAccountGetAccountFeesAnticipationCreditCardDto> creditCard;

  @JsonProperty("bankSlip")
  private JsonNullable<ApiMyAccountGetAccountFeesAnticipationBankSlipDto> bankSlip;

  @JsonIgnore
  public ApiMyAccountGetAccountFeesAnticipationCreditCardDto getCreditCard() {
    return creditCard.orElse(null);
  }

  @JsonIgnore
  public ApiMyAccountGetAccountFeesAnticipationBankSlipDto getBankSlip() {
    return bankSlip.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiMyAccountGetAccountFeesAnticipationDtoBuilder {

    private JsonNullable<ApiMyAccountGetAccountFeesAnticipationCreditCardDto> creditCard = JsonNullable.undefined();

    @JsonProperty("creditCard")
    public ApiMyAccountGetAccountFeesAnticipationDtoBuilder creditCard(
      ApiMyAccountGetAccountFeesAnticipationCreditCardDto value
    ) {
      if (value == null) {
        throw new IllegalStateException("creditCard cannot be null");
      }
      this.creditCard = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiMyAccountGetAccountFeesAnticipationBankSlipDto> bankSlip = JsonNullable.undefined();

    @JsonProperty("bankSlip")
    public ApiMyAccountGetAccountFeesAnticipationDtoBuilder bankSlip(
      ApiMyAccountGetAccountFeesAnticipationBankSlipDto value
    ) {
      if (value == null) {
        throw new IllegalStateException("bankSlip cannot be null");
      }
      this.bankSlip = JsonNullable.of(value);
      return this;
    }
  }
}
