// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentSimulatePixResponseDto {

  /**
   * Net value
   */
  @JsonProperty("netValue")
  private JsonNullable<Double> netValue;

  /**
   * Rate in percentage
   */
  @JsonProperty("feePercentage")
  private JsonNullable<Double> feePercentage;

  /**
   * Fee value
   */
  @JsonProperty("feeValue")
  private JsonNullable<Double> feeValue;

  @JsonProperty("installment")
  private JsonNullable<ApiPaymentSimulateInstallmentResponseDto> installment;

  @JsonIgnore
  public Double getNetValue() {
    return netValue.orElse(null);
  }

  @JsonIgnore
  public Double getFeePercentage() {
    return feePercentage.orElse(null);
  }

  @JsonIgnore
  public Double getFeeValue() {
    return feeValue.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentSimulateInstallmentResponseDto getInstallment() {
    return installment.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiPaymentSimulatePixResponseDtoBuilder {

    private JsonNullable<Double> netValue = JsonNullable.undefined();

    @JsonProperty("netValue")
    public ApiPaymentSimulatePixResponseDtoBuilder netValue(Double value) {
      this.netValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> feePercentage = JsonNullable.undefined();

    @JsonProperty("feePercentage")
    public ApiPaymentSimulatePixResponseDtoBuilder feePercentage(Double value) {
      this.feePercentage = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> feeValue = JsonNullable.undefined();

    @JsonProperty("feeValue")
    public ApiPaymentSimulatePixResponseDtoBuilder feeValue(Double value) {
      this.feeValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentSimulateInstallmentResponseDto> installment = JsonNullable.undefined();

    @JsonProperty("installment")
    public ApiPaymentSimulatePixResponseDtoBuilder installment(ApiPaymentSimulateInstallmentResponseDto value) {
      this.installment = JsonNullable.of(value);
      return this;
    }
  }
}
