// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPixTransactionExternalAccountResponseDto {

  /**
   * Payment Institution Identifier
   */
  @JsonProperty("ispb")
  private JsonNullable<String> ispb;

  /**
   * Name of Payment Institution
   */
  @JsonProperty("ispbName")
  private JsonNullable<String> ispbName;

  /**
   * Receiver name
   */
  @JsonProperty("name")
  private JsonNullable<String> name;

  /**
   * CPF or CNPJ of the recipient
   */
  @JsonProperty("cpfCnpj")
  private JsonNullable<String> cpfCnpj;

  /**
   * Pix Key
   */
  @JsonProperty("addressKey")
  private JsonNullable<String> addressKey;

  /**
   * Pix key type
   */
  @JsonProperty("addressKeyType")
  private JsonNullable<ApiPixTransactionExternalAccountResponsePixAddressKeyType> addressKeyType;

  @JsonIgnore
  public String getIspb() {
    return ispb.orElse(null);
  }

  @JsonIgnore
  public String getIspbName() {
    return ispbName.orElse(null);
  }

  @JsonIgnore
  public String getName() {
    return name.orElse(null);
  }

  @JsonIgnore
  public String getCpfCnpj() {
    return cpfCnpj.orElse(null);
  }

  @JsonIgnore
  public String getAddressKey() {
    return addressKey.orElse(null);
  }

  @JsonIgnore
  public ApiPixTransactionExternalAccountResponsePixAddressKeyType getAddressKeyType() {
    return addressKeyType.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiPixTransactionExternalAccountResponseDtoBuilder {

    private JsonNullable<String> ispb = JsonNullable.undefined();

    @JsonProperty("ispb")
    public ApiPixTransactionExternalAccountResponseDtoBuilder ispb(String value) {
      this.ispb = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> ispbName = JsonNullable.undefined();

    @JsonProperty("ispbName")
    public ApiPixTransactionExternalAccountResponseDtoBuilder ispbName(String value) {
      this.ispbName = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> name = JsonNullable.undefined();

    @JsonProperty("name")
    public ApiPixTransactionExternalAccountResponseDtoBuilder name(String value) {
      this.name = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> cpfCnpj = JsonNullable.undefined();

    @JsonProperty("cpfCnpj")
    public ApiPixTransactionExternalAccountResponseDtoBuilder cpfCnpj(String value) {
      this.cpfCnpj = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> addressKey = JsonNullable.undefined();

    @JsonProperty("addressKey")
    public ApiPixTransactionExternalAccountResponseDtoBuilder addressKey(String value) {
      this.addressKey = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPixTransactionExternalAccountResponsePixAddressKeyType> addressKeyType =
      JsonNullable.undefined();

    @JsonProperty("addressKeyType")
    public ApiPixTransactionExternalAccountResponseDtoBuilder addressKeyType(
      ApiPixTransactionExternalAccountResponsePixAddressKeyType value
    ) {
      this.addressKeyType = JsonNullable.of(value);
      return this;
    }
  }
}
