// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentCampaignUpdateRequestDto {

  /**
   * Payment link name
   */
  @JsonProperty("name")
  private JsonNullable<String> name;

  /**
   * Payments link description
   */
  @JsonProperty("description")
  private JsonNullable<String> description;

  /**
   * End date
   */
  @JsonProperty("endDate")
  private JsonNullable<String> endDate;

  /**
   * Value of the payment link, if not informed, the payer can inform how much they want to pay
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Determines whether the payments link is active
   */
  @JsonProperty("active")
  private JsonNullable<Boolean> active;

  /**
   * Allowed payment method
   */
  @JsonProperty("billingType")
  private JsonNullable<ApiPaymentCampaignUpdateRequestBillingType> billingType;

  /**
   * Charge type
   */
  @JsonProperty("chargeType")
  private JsonNullable<ApiPaymentCampaignUpdateRequestChargeType> chargeType;

  /**
   * Number of business days that your customer can pay after the invoice is generated (For payment method such as Boleto)
   */
  @JsonProperty("dueDateLimitDays")
  private JsonNullable<Long> dueDateLimitDays;

  /**
   * Billing frequency, if the chargeType is RECURRENT
   */
  @JsonProperty("subscriptionCycle")
  private JsonNullable<ApiPaymentCampaignUpdateRequestCycle> subscriptionCycle;

  /**
   * Maximum number of installments that your customer can pay in installments for the payment link if the billing method selected is Installments. If not informed, the default value will be 1 installment
   */
  @JsonProperty("maxInstallmentCount")
  private JsonNullable<Long> maxInstallmentCount;

  /**
   * Free search field.
   */
  @JsonProperty("externalReference")
  private JsonNullable<String> externalReference;

  /**
   * Defines whether customers registered via the payments link will have notifications enabled. If not informed, the default value will be true
   */
  @JsonProperty("notificationEnabled")
  private JsonNullable<Boolean> notificationEnabled;

  @JsonProperty("callback")
  private JsonNullable<ApiPaymentCallbackRequestDto> callback;

  @JsonIgnore
  public String getName() {
    return name.orElse(null);
  }

  @JsonIgnore
  public String getDescription() {
    return description.orElse(null);
  }

  @JsonIgnore
  public String getEndDate() {
    return endDate.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public Boolean getActive() {
    return active.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCampaignUpdateRequestBillingType getBillingType() {
    return billingType.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCampaignUpdateRequestChargeType getChargeType() {
    return chargeType.orElse(null);
  }

  @JsonIgnore
  public Long getDueDateLimitDays() {
    return dueDateLimitDays.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCampaignUpdateRequestCycle getSubscriptionCycle() {
    return subscriptionCycle.orElse(null);
  }

  @JsonIgnore
  public Long getMaxInstallmentCount() {
    return maxInstallmentCount.orElse(null);
  }

  @JsonIgnore
  public String getExternalReference() {
    return externalReference.orElse(null);
  }

  @JsonIgnore
  public Boolean getNotificationEnabled() {
    return notificationEnabled.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCallbackRequestDto getCallback() {
    return callback.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiPaymentCampaignUpdateRequestDtoBuilder {

    private JsonNullable<String> name = JsonNullable.undefined();

    @JsonProperty("name")
    public ApiPaymentCampaignUpdateRequestDtoBuilder name(String value) {
      this.name = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> description = JsonNullable.undefined();

    @JsonProperty("description")
    public ApiPaymentCampaignUpdateRequestDtoBuilder description(String value) {
      this.description = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> endDate = JsonNullable.undefined();

    @JsonProperty("endDate")
    public ApiPaymentCampaignUpdateRequestDtoBuilder endDate(String value) {
      this.endDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public ApiPaymentCampaignUpdateRequestDtoBuilder value(Double value) {
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> active = JsonNullable.undefined();

    @JsonProperty("active")
    public ApiPaymentCampaignUpdateRequestDtoBuilder active(Boolean value) {
      this.active = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCampaignUpdateRequestBillingType> billingType = JsonNullable.undefined();

    @JsonProperty("billingType")
    public ApiPaymentCampaignUpdateRequestDtoBuilder billingType(ApiPaymentCampaignUpdateRequestBillingType value) {
      this.billingType = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCampaignUpdateRequestChargeType> chargeType = JsonNullable.undefined();

    @JsonProperty("chargeType")
    public ApiPaymentCampaignUpdateRequestDtoBuilder chargeType(ApiPaymentCampaignUpdateRequestChargeType value) {
      this.chargeType = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> dueDateLimitDays = JsonNullable.undefined();

    @JsonProperty("dueDateLimitDays")
    public ApiPaymentCampaignUpdateRequestDtoBuilder dueDateLimitDays(Long value) {
      this.dueDateLimitDays = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCampaignUpdateRequestCycle> subscriptionCycle = JsonNullable.undefined();

    @JsonProperty("subscriptionCycle")
    public ApiPaymentCampaignUpdateRequestDtoBuilder subscriptionCycle(ApiPaymentCampaignUpdateRequestCycle value) {
      this.subscriptionCycle = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> maxInstallmentCount = JsonNullable.of(1L);

    @JsonProperty("maxInstallmentCount")
    public ApiPaymentCampaignUpdateRequestDtoBuilder maxInstallmentCount(Long value) {
      this.maxInstallmentCount = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> externalReference = JsonNullable.undefined();

    @JsonProperty("externalReference")
    public ApiPaymentCampaignUpdateRequestDtoBuilder externalReference(String value) {
      this.externalReference = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> notificationEnabled = JsonNullable.of(true);

    @JsonProperty("notificationEnabled")
    public ApiPaymentCampaignUpdateRequestDtoBuilder notificationEnabled(Boolean value) {
      this.notificationEnabled = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCallbackRequestDto> callback = JsonNullable.undefined();

    @JsonProperty("callback")
    public ApiPaymentCampaignUpdateRequestDtoBuilder callback(ApiPaymentCallbackRequestDto value) {
      this.callback = JsonNullable.of(value);
      return this;
    }
  }
}
