// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentViewingInfoResponseDto {

  /**
   * Invoice viewing date and time
   */
  @JsonProperty("invoiceViewedDate")
  private JsonNullable<String> invoiceViewedDate;

  /**
   * Bill viewing date and time
   */
  @JsonProperty("boletoViewedDate")
  private JsonNullable<String> boletoViewedDate;

  @JsonIgnore
  public String getInvoiceViewedDate() {
    return invoiceViewedDate.orElse(null);
  }

  @JsonIgnore
  public String getBoletoViewedDate() {
    return boletoViewedDate.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiPaymentViewingInfoResponseDtoBuilder {

    private JsonNullable<String> invoiceViewedDate = JsonNullable.undefined();

    @JsonProperty("invoiceViewedDate")
    public ApiPaymentViewingInfoResponseDtoBuilder invoiceViewedDate(String value) {
      if (value == null) {
        throw new IllegalStateException("invoiceViewedDate cannot be null");
      }
      this.invoiceViewedDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> boletoViewedDate = JsonNullable.undefined();

    @JsonProperty("boletoViewedDate")
    public ApiPaymentViewingInfoResponseDtoBuilder boletoViewedDate(String value) {
      if (value == null) {
        throw new IllegalStateException("boletoViewedDate cannot be null");
      }
      this.boletoViewedDate = JsonNullable.of(value);
      return this;
    }
  }
}
