// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentCustodyGetResponseDto {

  /**
   * Unique payment escrow identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Payment escrow status
   */
  @JsonProperty("status")
  private JsonNullable<ApiPaymentCustodyGetResponsePaymentCustodyStatus> status;

  /**
   * Payment escrow expiration date
   */
  @JsonProperty("expirationDate")
  private JsonNullable<String> expirationDate;

  /**
   * Payment escrow finish date
   */
  @JsonProperty("finishDate")
  private JsonNullable<String> finishDate;

  /**
   * Payment escrow finish reason
   */
  @JsonProperty("finishReason")
  private JsonNullable<ApiPaymentCustodyGetResponsePaymentCustodyFinishReason> finishReason;

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCustodyGetResponsePaymentCustodyStatus getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public String getExpirationDate() {
    return expirationDate.orElse(null);
  }

  @JsonIgnore
  public String getFinishDate() {
    return finishDate.orElse(null);
  }

  @JsonIgnore
  public ApiPaymentCustodyGetResponsePaymentCustodyFinishReason getFinishReason() {
    return finishReason.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiPaymentCustodyGetResponseDtoBuilder {

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public ApiPaymentCustodyGetResponseDtoBuilder id(String value) {
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCustodyGetResponsePaymentCustodyStatus> status = JsonNullable.undefined();

    @JsonProperty("status")
    public ApiPaymentCustodyGetResponseDtoBuilder status(ApiPaymentCustodyGetResponsePaymentCustodyStatus value) {
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> expirationDate = JsonNullable.undefined();

    @JsonProperty("expirationDate")
    public ApiPaymentCustodyGetResponseDtoBuilder expirationDate(String value) {
      this.expirationDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> finishDate = JsonNullable.undefined();

    @JsonProperty("finishDate")
    public ApiPaymentCustodyGetResponseDtoBuilder finishDate(String value) {
      this.finishDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiPaymentCustodyGetResponsePaymentCustodyFinishReason> finishReason =
      JsonNullable.undefined();

    @JsonProperty("finishReason")
    public ApiPaymentCustodyGetResponseDtoBuilder finishReason(
      ApiPaymentCustodyGetResponsePaymentCustodyFinishReason value
    ) {
      this.finishReason = JsonNullable.of(value);
      return this;
    }
  }
}
