// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiReceivableAnticipationSimulateResponseDto {

  /**
   * Unique identifier of the installment to be anticipated
   */
  @JsonProperty("installment")
  private JsonNullable<String> installment;

  /**
   * Unique identifier of the payment to be anticipated
   */
  @JsonProperty("payment")
  private JsonNullable<String> payment;

  /**
   * Anticipation request date
   */
  @JsonProperty("anticipationDate")
  private JsonNullable<String> anticipationDate;

  /**
   * Request due date
   */
  @JsonProperty("dueDate")
  private JsonNullable<String> dueDate;

  /**
   * Anticipation fee
   */
  @JsonProperty("fee")
  private JsonNullable<Double> fee;

  /**
   * Number of days that were anticipated
   */
  @JsonProperty("anticipationDays")
  private JsonNullable<Long> anticipationDays;

  /**
   * Net value discounted the anticipation fee
   */
  @JsonProperty("netValue")
  private JsonNullable<Double> netValue;

  /**
   * Total amount of the payment to be anticipated
   */
  @JsonProperty("totalValue")
  private JsonNullable<Double> totalValue;

  /**
   * Anticipation value
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Determines the obligation to send electronic invoices or service provision contracts when requesting anticipation payment
   */
  @JsonProperty("isDocumentationRequired")
  private JsonNullable<Boolean> isDocumentationRequired;

  @JsonIgnore
  public String getInstallment() {
    return installment.orElse(null);
  }

  @JsonIgnore
  public String getPayment() {
    return payment.orElse(null);
  }

  @JsonIgnore
  public String getAnticipationDate() {
    return anticipationDate.orElse(null);
  }

  @JsonIgnore
  public String getDueDate() {
    return dueDate.orElse(null);
  }

  @JsonIgnore
  public Double getFee() {
    return fee.orElse(null);
  }

  @JsonIgnore
  public Long getAnticipationDays() {
    return anticipationDays.orElse(null);
  }

  @JsonIgnore
  public Double getNetValue() {
    return netValue.orElse(null);
  }

  @JsonIgnore
  public Double getTotalValue() {
    return totalValue.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public Boolean getIsDocumentationRequired() {
    return isDocumentationRequired.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiReceivableAnticipationSimulateResponseDtoBuilder {

    private JsonNullable<String> installment = JsonNullable.undefined();

    @JsonProperty("installment")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder installment(String value) {
      if (value == null) {
        throw new IllegalStateException("installment cannot be null");
      }
      this.installment = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> payment = JsonNullable.undefined();

    @JsonProperty("payment")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder payment(String value) {
      if (value == null) {
        throw new IllegalStateException("payment cannot be null");
      }
      this.payment = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> anticipationDate = JsonNullable.undefined();

    @JsonProperty("anticipationDate")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder anticipationDate(String value) {
      if (value == null) {
        throw new IllegalStateException("anticipationDate cannot be null");
      }
      this.anticipationDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dueDate = JsonNullable.undefined();

    @JsonProperty("dueDate")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder dueDate(String value) {
      if (value == null) {
        throw new IllegalStateException("dueDate cannot be null");
      }
      this.dueDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> fee = JsonNullable.undefined();

    @JsonProperty("fee")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder fee(Double value) {
      if (value == null) {
        throw new IllegalStateException("fee cannot be null");
      }
      this.fee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> anticipationDays = JsonNullable.undefined();

    @JsonProperty("anticipationDays")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder anticipationDays(Long value) {
      if (value == null) {
        throw new IllegalStateException("anticipationDays cannot be null");
      }
      this.anticipationDays = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> netValue = JsonNullable.undefined();

    @JsonProperty("netValue")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder netValue(Double value) {
      if (value == null) {
        throw new IllegalStateException("netValue cannot be null");
      }
      this.netValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> totalValue = JsonNullable.undefined();

    @JsonProperty("totalValue")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder totalValue(Double value) {
      if (value == null) {
        throw new IllegalStateException("totalValue cannot be null");
      }
      this.totalValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder value(Double value) {
      if (value == null) {
        throw new IllegalStateException("value cannot be null");
      }
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> isDocumentationRequired = JsonNullable.undefined();

    @JsonProperty("isDocumentationRequired")
    public ApiReceivableAnticipationSimulateResponseDtoBuilder isDocumentationRequired(Boolean value) {
      if (value == null) {
        throw new IllegalStateException("isDocumentationRequired cannot be null");
      }
      this.isDocumentationRequired = JsonNullable.of(value);
      return this;
    }
  }
}
