// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiSubscriptionInvoiceConfigUpdateRequestDto {

  /**
   * Deductions. Deductions do not change the total value of the invoice, but they do change the ISS calculation basis.
   */
  @JsonProperty("deductions")
  private JsonNullable<Double> deductions;

  /**
   * When the invoice will be issued
   */
  @JsonProperty("effectiveDatePeriod")
  private JsonNullable<ApiSubscriptionInvoiceConfigUpdateRequestDtoEffectiveDatePeriod> effectiveDatePeriod;

  /**
   * Issue only for paid charges
   */
  @JsonProperty("receivedOnly")
  private JsonNullable<Boolean> receivedOnly;

  /**
   * Number of days before billing due date
   */
  @JsonProperty("daysBeforeDueDate")
  private JsonNullable<Long> daysBeforeDueDate;

  /**
   * Additional notes on the invoice
   */
  @JsonProperty("observations")
  private JsonNullable<String> observations;

  @JsonProperty("taxes")
  private JsonNullable<ApiCustomerInvoiceTaxesDto> taxes;

  @JsonIgnore
  public Double getDeductions() {
    return deductions.orElse(null);
  }

  @JsonIgnore
  public ApiSubscriptionInvoiceConfigUpdateRequestDtoEffectiveDatePeriod getEffectiveDatePeriod() {
    return effectiveDatePeriod.orElse(null);
  }

  @JsonIgnore
  public Boolean getReceivedOnly() {
    return receivedOnly.orElse(null);
  }

  @JsonIgnore
  public Long getDaysBeforeDueDate() {
    return daysBeforeDueDate.orElse(null);
  }

  @JsonIgnore
  public String getObservations() {
    return observations.orElse(null);
  }

  @JsonIgnore
  public ApiCustomerInvoiceTaxesDto getTaxes() {
    return taxes.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder {

    private JsonNullable<Double> deductions = JsonNullable.undefined();

    @JsonProperty("deductions")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder deductions(Double value) {
      if (value == null) {
        throw new IllegalStateException("deductions cannot be null");
      }
      this.deductions = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiSubscriptionInvoiceConfigUpdateRequestDtoEffectiveDatePeriod> effectiveDatePeriod =
      JsonNullable.undefined();

    @JsonProperty("effectiveDatePeriod")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder effectiveDatePeriod(
      ApiSubscriptionInvoiceConfigUpdateRequestDtoEffectiveDatePeriod value
    ) {
      if (value == null) {
        throw new IllegalStateException("effectiveDatePeriod cannot be null");
      }
      this.effectiveDatePeriod = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> receivedOnly = JsonNullable.undefined();

    @JsonProperty("receivedOnly")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder receivedOnly(Boolean value) {
      if (value == null) {
        throw new IllegalStateException("receivedOnly cannot be null");
      }
      this.receivedOnly = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> daysBeforeDueDate = JsonNullable.undefined();

    @JsonProperty("daysBeforeDueDate")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder daysBeforeDueDate(Long value) {
      if (value == null) {
        throw new IllegalStateException("daysBeforeDueDate cannot be null");
      }
      this.daysBeforeDueDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> observations = JsonNullable.undefined();

    @JsonProperty("observations")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder observations(String value) {
      if (value == null) {
        throw new IllegalStateException("observations cannot be null");
      }
      this.observations = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiCustomerInvoiceTaxesDto> taxes = JsonNullable.undefined();

    @JsonProperty("taxes")
    public ApiSubscriptionInvoiceConfigUpdateRequestDtoBuilder taxes(ApiCustomerInvoiceTaxesDto value) {
      if (value == null) {
        throw new IllegalStateException("taxes cannot be null");
      }
      this.taxes = JsonNullable.of(value);
      return this;
    }
  }
}
