// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Subscription status
 */
@Getter
@AllArgsConstructor
public enum ApiSubscriptionSaveWithCreditCardResponseSubscriptionStatus {
  ACTIVE("ACTIVE"),
  EXPIRED("EXPIRED"),
  INACTIVE("INACTIVE");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiSubscriptionSaveWithCreditCardResponseSubscriptionStatus fromValue(String value) {
    return Arrays.stream(ApiSubscriptionSaveWithCreditCardResponseSubscriptionStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
