// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Type of transfer
 */
@Getter
@AllArgsConstructor
public enum ApiTransferSaveInternalTransferResponseDtoType {
  PIX("PIX"),
  TED("TED"),
  INTERNAL("INTERNAL");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiTransferSaveInternalTransferResponseDtoType fromValue(String value) {
    return Arrays.stream(ApiTransferSaveInternalTransferResponseDtoType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
