// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiTransferSaveInternalTransferResponseDto {

  /**
   * Object type
   */
  @JsonProperty("object")
  private JsonNullable<String> object;

  /**
   * Unique transfer identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Type of transfer
   */
  @JsonProperty("type")
  private JsonNullable<ApiTransferSaveInternalTransferResponseDtoType> type;

  /**
   * Transfer request date
   */
  @JsonProperty("dateCreated")
  private JsonNullable<String> dateCreated;

  /**
   * Transfer amount
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Net value minus transfer fee
   */
  @JsonProperty("netValue")
  private JsonNullable<Double> netValue;

  /**
   * Transfer status
   */
  @JsonProperty("status")
  private JsonNullable<ApiTransferSaveInternalTransferResponseTransferStatus> status;

  /**
   * Transfer rate
   */
  @JsonProperty("transferFee")
  private JsonNullable<Double> transferFee;

  /**
   * Effective date
   */
  @JsonProperty("effectiveDate")
  private JsonNullable<String> effectiveDate;

  /**
   * Schedule date
   */
  @JsonProperty("scheduleDate")
  private JsonNullable<String> scheduleDate;

  /**
   * Unique identifier of the Pix transaction at the Central Bank
   */
  @JsonProperty("endToEndIdentifier")
  private JsonNullable<String> endToEndIdentifier;

  /**
   * `false` when awaiting authorization via SMS Token
   */
  @JsonProperty("authorized")
  private JsonNullable<Boolean> authorized;

  /**
   * Reason for transfer failure
   */
  @JsonProperty("failReason")
  private JsonNullable<String> failReason;

  /**
   * Transfer identifier in your system
   */
  @JsonProperty("externalReference")
  private JsonNullable<String> externalReference;

  /**
   * Proof of transfer will be available after the transfer is confirmed
   */
  @JsonProperty("transactionReceiptUrl")
  private JsonNullable<String> transactionReceiptUrl;

  /**
   * Transfer method
   */
  @JsonProperty("operationType")
  private JsonNullable<ApiTransferSaveInternalTransferResponseTransferType> operationType;

  /**
   * Transfer description
   */
  @JsonProperty("description")
  private JsonNullable<String> description;

  /**
   * Unique recurrence identifier in Asaas
   */
  @JsonProperty("recurring")
  private JsonNullable<String> recurring;

  /**
   * Unique wallet identifier to split charges or transfer between Asaas accounts
   */
  @JsonProperty("walletId")
  private JsonNullable<String> walletId;

  @JsonProperty("account")
  private JsonNullable<ApiTransferSaveInternalTransferAccountDto> account;

  @JsonIgnore
  public String getObject() {
    return object.orElse(null);
  }

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public ApiTransferSaveInternalTransferResponseDtoType getType() {
    return type.orElse(null);
  }

  @JsonIgnore
  public String getDateCreated() {
    return dateCreated.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public Double getNetValue() {
    return netValue.orElse(null);
  }

  @JsonIgnore
  public ApiTransferSaveInternalTransferResponseTransferStatus getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public Double getTransferFee() {
    return transferFee.orElse(null);
  }

  @JsonIgnore
  public String getEffectiveDate() {
    return effectiveDate.orElse(null);
  }

  @JsonIgnore
  public String getScheduleDate() {
    return scheduleDate.orElse(null);
  }

  @JsonIgnore
  public String getEndToEndIdentifier() {
    return endToEndIdentifier.orElse(null);
  }

  @JsonIgnore
  public Boolean getAuthorized() {
    return authorized.orElse(null);
  }

  @JsonIgnore
  public String getFailReason() {
    return failReason.orElse(null);
  }

  @JsonIgnore
  public String getExternalReference() {
    return externalReference.orElse(null);
  }

  @JsonIgnore
  public String getTransactionReceiptUrl() {
    return transactionReceiptUrl.orElse(null);
  }

  @JsonIgnore
  public ApiTransferSaveInternalTransferResponseTransferType getOperationType() {
    return operationType.orElse(null);
  }

  @JsonIgnore
  public String getDescription() {
    return description.orElse(null);
  }

  @JsonIgnore
  public String getRecurring() {
    return recurring.orElse(null);
  }

  @JsonIgnore
  public String getWalletId() {
    return walletId.orElse(null);
  }

  @JsonIgnore
  public ApiTransferSaveInternalTransferAccountDto getAccount() {
    return account.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiTransferSaveInternalTransferResponseDtoBuilder {

    private JsonNullable<String> object = JsonNullable.undefined();

    @JsonProperty("object")
    public ApiTransferSaveInternalTransferResponseDtoBuilder object(String value) {
      this.object = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public ApiTransferSaveInternalTransferResponseDtoBuilder id(String value) {
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferSaveInternalTransferResponseDtoType> type = JsonNullable.undefined();

    @JsonProperty("type")
    public ApiTransferSaveInternalTransferResponseDtoBuilder type(
      ApiTransferSaveInternalTransferResponseDtoType value
    ) {
      this.type = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dateCreated = JsonNullable.undefined();

    @JsonProperty("dateCreated")
    public ApiTransferSaveInternalTransferResponseDtoBuilder dateCreated(String value) {
      this.dateCreated = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public ApiTransferSaveInternalTransferResponseDtoBuilder value(Double value) {
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> netValue = JsonNullable.undefined();

    @JsonProperty("netValue")
    public ApiTransferSaveInternalTransferResponseDtoBuilder netValue(Double value) {
      this.netValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferSaveInternalTransferResponseTransferStatus> status = JsonNullable.undefined();

    @JsonProperty("status")
    public ApiTransferSaveInternalTransferResponseDtoBuilder status(
      ApiTransferSaveInternalTransferResponseTransferStatus value
    ) {
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> transferFee = JsonNullable.undefined();

    @JsonProperty("transferFee")
    public ApiTransferSaveInternalTransferResponseDtoBuilder transferFee(Double value) {
      this.transferFee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> effectiveDate = JsonNullable.undefined();

    @JsonProperty("effectiveDate")
    public ApiTransferSaveInternalTransferResponseDtoBuilder effectiveDate(String value) {
      this.effectiveDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> scheduleDate = JsonNullable.undefined();

    @JsonProperty("scheduleDate")
    public ApiTransferSaveInternalTransferResponseDtoBuilder scheduleDate(String value) {
      this.scheduleDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> endToEndIdentifier = JsonNullable.undefined();

    @JsonProperty("endToEndIdentifier")
    public ApiTransferSaveInternalTransferResponseDtoBuilder endToEndIdentifier(String value) {
      this.endToEndIdentifier = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> authorized = JsonNullable.undefined();

    @JsonProperty("authorized")
    public ApiTransferSaveInternalTransferResponseDtoBuilder authorized(Boolean value) {
      this.authorized = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> failReason = JsonNullable.undefined();

    @JsonProperty("failReason")
    public ApiTransferSaveInternalTransferResponseDtoBuilder failReason(String value) {
      this.failReason = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> externalReference = JsonNullable.undefined();

    @JsonProperty("externalReference")
    public ApiTransferSaveInternalTransferResponseDtoBuilder externalReference(String value) {
      this.externalReference = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> transactionReceiptUrl = JsonNullable.undefined();

    @JsonProperty("transactionReceiptUrl")
    public ApiTransferSaveInternalTransferResponseDtoBuilder transactionReceiptUrl(String value) {
      this.transactionReceiptUrl = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferSaveInternalTransferResponseTransferType> operationType = JsonNullable.undefined();

    @JsonProperty("operationType")
    public ApiTransferSaveInternalTransferResponseDtoBuilder operationType(
      ApiTransferSaveInternalTransferResponseTransferType value
    ) {
      this.operationType = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> description = JsonNullable.undefined();

    @JsonProperty("description")
    public ApiTransferSaveInternalTransferResponseDtoBuilder description(String value) {
      this.description = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> recurring = JsonNullable.undefined();

    @JsonProperty("recurring")
    public ApiTransferSaveInternalTransferResponseDtoBuilder recurring(String value) {
      this.recurring = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> walletId = JsonNullable.undefined();

    @JsonProperty("walletId")
    public ApiTransferSaveInternalTransferResponseDtoBuilder walletId(String value) {
      this.walletId = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferSaveInternalTransferAccountDto> account = JsonNullable.undefined();

    @JsonProperty("account")
    public ApiTransferSaveInternalTransferResponseDtoBuilder account(ApiTransferSaveInternalTransferAccountDto value) {
      this.account = JsonNullable.of(value);
      return this;
    }
  }
}
