// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Frequency
 */
@Getter
@AllArgsConstructor
public enum ApiTransferRecurringSaveRequestRecurringCheckoutScheduleFrequency {
  WEEKLY("WEEKLY"),
  MONTHLY("MONTHLY");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiTransferRecurringSaveRequestRecurringCheckoutScheduleFrequency fromValue(String value) {
    return Arrays.stream(ApiTransferRecurringSaveRequestRecurringCheckoutScheduleFrequency.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
