// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiTransferGetResponseDto {

  /**
   * Object type
   */
  @JsonProperty("object")
  private JsonNullable<String> object;

  /**
   * Unique transfer identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Type of transfer
   */
  @JsonProperty("type")
  private JsonNullable<ApiTransferGetResponseDtoType> type;

  /**
   * Transfer request date
   */
  @JsonProperty("dateCreated")
  private JsonNullable<String> dateCreated;

  /**
   * Transfer amount
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Net value minus transfer fee
   */
  @JsonProperty("netValue")
  private JsonNullable<Double> netValue;

  /**
   * Transfer status
   */
  @JsonProperty("status")
  private JsonNullable<ApiTransferGetResponseTransferStatus> status;

  /**
   * Transfer rate
   */
  @JsonProperty("transferFee")
  private JsonNullable<Double> transferFee;

  /**
   * Effective date
   */
  @JsonProperty("effectiveDate")
  private JsonNullable<String> effectiveDate;

  /**
   * Schedule date
   */
  @JsonProperty("scheduleDate")
  private JsonNullable<String> scheduleDate;

  /**
   * Unique identifier of the Pix transaction at the Central Bank
   */
  @JsonProperty("endToEndIdentifier")
  private JsonNullable<String> endToEndIdentifier;

  /**
   * `false` when awaiting authorization via SMS Token
   */
  @JsonProperty("authorized")
  private JsonNullable<Boolean> authorized;

  /**
   * Reason for transfer failure
   */
  @JsonProperty("failReason")
  private JsonNullable<String> failReason;

  /**
   * Transfer identifier in your system
   */
  @JsonProperty("externalReference")
  private JsonNullable<String> externalReference;

  /**
   * Proof of transfer will be available after the transfer is confirmed
   */
  @JsonProperty("transactionReceiptUrl")
  private JsonNullable<String> transactionReceiptUrl;

  /**
   * Transfer method
   */
  @JsonProperty("operationType")
  private JsonNullable<ApiTransferGetResponseTransferType> operationType;

  /**
   * Transfer description
   */
  @JsonProperty("description")
  private JsonNullable<String> description;

  /**
   * Unique recurrence identifier in Asaas
   */
  @JsonProperty("recurring")
  private JsonNullable<String> recurring;

  @JsonProperty("bankAccount")
  private JsonNullable<ApiTransferBankAccountGetResponseDto> bankAccount;

  @JsonIgnore
  public String getObject() {
    return object.orElse(null);
  }

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public ApiTransferGetResponseDtoType getType() {
    return type.orElse(null);
  }

  @JsonIgnore
  public String getDateCreated() {
    return dateCreated.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public Double getNetValue() {
    return netValue.orElse(null);
  }

  @JsonIgnore
  public ApiTransferGetResponseTransferStatus getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public Double getTransferFee() {
    return transferFee.orElse(null);
  }

  @JsonIgnore
  public String getEffectiveDate() {
    return effectiveDate.orElse(null);
  }

  @JsonIgnore
  public String getScheduleDate() {
    return scheduleDate.orElse(null);
  }

  @JsonIgnore
  public String getEndToEndIdentifier() {
    return endToEndIdentifier.orElse(null);
  }

  @JsonIgnore
  public Boolean getAuthorized() {
    return authorized.orElse(null);
  }

  @JsonIgnore
  public String getFailReason() {
    return failReason.orElse(null);
  }

  @JsonIgnore
  public String getExternalReference() {
    return externalReference.orElse(null);
  }

  @JsonIgnore
  public String getTransactionReceiptUrl() {
    return transactionReceiptUrl.orElse(null);
  }

  @JsonIgnore
  public ApiTransferGetResponseTransferType getOperationType() {
    return operationType.orElse(null);
  }

  @JsonIgnore
  public String getDescription() {
    return description.orElse(null);
  }

  @JsonIgnore
  public String getRecurring() {
    return recurring.orElse(null);
  }

  @JsonIgnore
  public ApiTransferBankAccountGetResponseDto getBankAccount() {
    return bankAccount.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiTransferGetResponseDtoBuilder {

    private JsonNullable<String> object = JsonNullable.undefined();

    @JsonProperty("object")
    public ApiTransferGetResponseDtoBuilder object(String value) {
      if (value == null) {
        throw new IllegalStateException("object cannot be null");
      }
      this.object = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public ApiTransferGetResponseDtoBuilder id(String value) {
      if (value == null) {
        throw new IllegalStateException("id cannot be null");
      }
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferGetResponseDtoType> type = JsonNullable.undefined();

    @JsonProperty("type")
    public ApiTransferGetResponseDtoBuilder type(ApiTransferGetResponseDtoType value) {
      if (value == null) {
        throw new IllegalStateException("type cannot be null");
      }
      this.type = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dateCreated = JsonNullable.undefined();

    @JsonProperty("dateCreated")
    public ApiTransferGetResponseDtoBuilder dateCreated(String value) {
      if (value == null) {
        throw new IllegalStateException("dateCreated cannot be null");
      }
      this.dateCreated = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public ApiTransferGetResponseDtoBuilder value(Double value) {
      if (value == null) {
        throw new IllegalStateException("value cannot be null");
      }
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> netValue = JsonNullable.undefined();

    @JsonProperty("netValue")
    public ApiTransferGetResponseDtoBuilder netValue(Double value) {
      if (value == null) {
        throw new IllegalStateException("netValue cannot be null");
      }
      this.netValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferGetResponseTransferStatus> status = JsonNullable.undefined();

    @JsonProperty("status")
    public ApiTransferGetResponseDtoBuilder status(ApiTransferGetResponseTransferStatus value) {
      if (value == null) {
        throw new IllegalStateException("status cannot be null");
      }
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> transferFee = JsonNullable.undefined();

    @JsonProperty("transferFee")
    public ApiTransferGetResponseDtoBuilder transferFee(Double value) {
      if (value == null) {
        throw new IllegalStateException("transferFee cannot be null");
      }
      this.transferFee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> effectiveDate = JsonNullable.undefined();

    @JsonProperty("effectiveDate")
    public ApiTransferGetResponseDtoBuilder effectiveDate(String value) {
      if (value == null) {
        throw new IllegalStateException("effectiveDate cannot be null");
      }
      this.effectiveDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> scheduleDate = JsonNullable.undefined();

    @JsonProperty("scheduleDate")
    public ApiTransferGetResponseDtoBuilder scheduleDate(String value) {
      if (value == null) {
        throw new IllegalStateException("scheduleDate cannot be null");
      }
      this.scheduleDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> endToEndIdentifier = JsonNullable.undefined();

    @JsonProperty("endToEndIdentifier")
    public ApiTransferGetResponseDtoBuilder endToEndIdentifier(String value) {
      if (value == null) {
        throw new IllegalStateException("endToEndIdentifier cannot be null");
      }
      this.endToEndIdentifier = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> authorized = JsonNullable.undefined();

    @JsonProperty("authorized")
    public ApiTransferGetResponseDtoBuilder authorized(Boolean value) {
      if (value == null) {
        throw new IllegalStateException("authorized cannot be null");
      }
      this.authorized = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> failReason = JsonNullable.undefined();

    @JsonProperty("failReason")
    public ApiTransferGetResponseDtoBuilder failReason(String value) {
      if (value == null) {
        throw new IllegalStateException("failReason cannot be null");
      }
      this.failReason = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> externalReference = JsonNullable.undefined();

    @JsonProperty("externalReference")
    public ApiTransferGetResponseDtoBuilder externalReference(String value) {
      if (value == null) {
        throw new IllegalStateException("externalReference cannot be null");
      }
      this.externalReference = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> transactionReceiptUrl = JsonNullable.undefined();

    @JsonProperty("transactionReceiptUrl")
    public ApiTransferGetResponseDtoBuilder transactionReceiptUrl(String value) {
      if (value == null) {
        throw new IllegalStateException("transactionReceiptUrl cannot be null");
      }
      this.transactionReceiptUrl = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferGetResponseTransferType> operationType = JsonNullable.undefined();

    @JsonProperty("operationType")
    public ApiTransferGetResponseDtoBuilder operationType(ApiTransferGetResponseTransferType value) {
      if (value == null) {
        throw new IllegalStateException("operationType cannot be null");
      }
      this.operationType = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> description = JsonNullable.undefined();

    @JsonProperty("description")
    public ApiTransferGetResponseDtoBuilder description(String value) {
      if (value == null) {
        throw new IllegalStateException("description cannot be null");
      }
      this.description = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> recurring = JsonNullable.undefined();

    @JsonProperty("recurring")
    public ApiTransferGetResponseDtoBuilder recurring(String value) {
      if (value == null) {
        throw new IllegalStateException("recurring cannot be null");
      }
      this.recurring = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<ApiTransferBankAccountGetResponseDto> bankAccount = JsonNullable.undefined();

    @JsonProperty("bankAccount")
    public ApiTransferGetResponseDtoBuilder bankAccount(ApiTransferBankAccountGetResponseDto value) {
      if (value == null) {
        throw new IllegalStateException("bankAccount cannot be null");
      }
      this.bankAccount = JsonNullable.of(value);
      return this;
    }
  }
}
