// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiTransferSaveInternalTransferAccountDto {

  /**
   * Target account name
   */
  @JsonProperty("name")
  private JsonNullable<String> name;

  /**
   * CPF or CNPJ of the destination account
   */
  @JsonProperty("cpfCnpj")
  private JsonNullable<String> cpfCnpj;

  /**
   * Target account branch code
   */
  @JsonProperty("agency")
  private JsonNullable<String> agency;

  /**
   * Target account number
   */
  @JsonProperty("account")
  private JsonNullable<String> account;

  /**
   * Target account digit
   */
  @JsonProperty("accountDigit")
  private JsonNullable<String> accountDigit;

  @JsonIgnore
  public String getName() {
    return name.orElse(null);
  }

  @JsonIgnore
  public String getCpfCnpj() {
    return cpfCnpj.orElse(null);
  }

  @JsonIgnore
  public String getAgency() {
    return agency.orElse(null);
  }

  @JsonIgnore
  public String getAccount() {
    return account.orElse(null);
  }

  @JsonIgnore
  public String getAccountDigit() {
    return accountDigit.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class ApiTransferSaveInternalTransferAccountDtoBuilder {

    private JsonNullable<String> name = JsonNullable.undefined();

    @JsonProperty("name")
    public ApiTransferSaveInternalTransferAccountDtoBuilder name(String value) {
      this.name = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> cpfCnpj = JsonNullable.undefined();

    @JsonProperty("cpfCnpj")
    public ApiTransferSaveInternalTransferAccountDtoBuilder cpfCnpj(String value) {
      this.cpfCnpj = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> agency = JsonNullable.undefined();

    @JsonProperty("agency")
    public ApiTransferSaveInternalTransferAccountDtoBuilder agency(String value) {
      this.agency = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> account = JsonNullable.undefined();

    @JsonProperty("account")
    public ApiTransferSaveInternalTransferAccountDtoBuilder account(String value) {
      this.account = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> accountDigit = JsonNullable.undefined();

    @JsonProperty("accountDigit")
    public ApiTransferSaveInternalTransferAccountDtoBuilder accountDigit(String value) {
      this.accountDigit = JsonNullable.of(value);
      return this;
    }
  }
}
