// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Information about the bill to be paid
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class BillSimulateBankSlipInfoResponseDto {

  /**
   * Digitable line
   */
  @JsonProperty("identificationField")
  private JsonNullable<String> identificationField;

  /**
   * Ticket value
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Due date
   */
  @JsonProperty("dueDate")
  private JsonNullable<String> dueDate;

  /**
   * Company/Body issuing the bill
   */
  @JsonProperty("companyName")
  private JsonNullable<String> companyName;

  /**
   * Code of the bank issuing the bill in the banking system
   */
  @JsonProperty("bank")
  private JsonNullable<String> bank;

  /**
   * CPF or CNPJ of the beneficiary
   */
  @JsonProperty("beneficiaryCpfCnpj")
  private JsonNullable<String> beneficiaryCpfCnpj;

  /**
   * Beneficiary's name
   */
  @JsonProperty("beneficiaryName")
  private JsonNullable<String> beneficiaryName;

  /**
   * Whether the value can be changed or not
   */
  @JsonProperty("allowChangeValue")
  private JsonNullable<Boolean> allowChangeValue;

  /**
   * Minimum value that can be changed
   */
  @JsonProperty("minValue")
  private JsonNullable<Double> minValue;

  /**
   * Maximum value that can be changed
   */
  @JsonProperty("maxValue")
  private JsonNullable<Double> maxValue;

  /**
   * Value of discounts
   */
  @JsonProperty("discountValue")
  private JsonNullable<Double> discountValue;

  /**
   * Interest amount
   */
  @JsonProperty("interestValue")
  private JsonNullable<Double> interestValue;

  /**
   * Fine value
   */
  @JsonProperty("fineValue")
  private JsonNullable<Double> fineValue;

  /**
   * Original bill value
   */
  @JsonProperty("originalValue")
  private JsonNullable<Double> originalValue;

  /**
   * Total value of discounts and rebates
   */
  @JsonProperty("totalDiscountValue")
  private JsonNullable<Double> totalDiscountValue;

  /**
   * Total amount of interest and fine
   */
  @JsonProperty("totalAdditionalValue")
  private JsonNullable<Double> totalAdditionalValue;

  /**
   * Informs if the ticket is expired
   */
  @JsonProperty("isOverdue")
  private JsonNullable<Boolean> isOverdue;

  @JsonIgnore
  public String getIdentificationField() {
    return identificationField.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public String getDueDate() {
    return dueDate.orElse(null);
  }

  @JsonIgnore
  public String getCompanyName() {
    return companyName.orElse(null);
  }

  @JsonIgnore
  public String getBank() {
    return bank.orElse(null);
  }

  @JsonIgnore
  public String getBeneficiaryCpfCnpj() {
    return beneficiaryCpfCnpj.orElse(null);
  }

  @JsonIgnore
  public String getBeneficiaryName() {
    return beneficiaryName.orElse(null);
  }

  @JsonIgnore
  public Boolean getAllowChangeValue() {
    return allowChangeValue.orElse(null);
  }

  @JsonIgnore
  public Double getMinValue() {
    return minValue.orElse(null);
  }

  @JsonIgnore
  public Double getMaxValue() {
    return maxValue.orElse(null);
  }

  @JsonIgnore
  public Double getDiscountValue() {
    return discountValue.orElse(null);
  }

  @JsonIgnore
  public Double getInterestValue() {
    return interestValue.orElse(null);
  }

  @JsonIgnore
  public Double getFineValue() {
    return fineValue.orElse(null);
  }

  @JsonIgnore
  public Double getOriginalValue() {
    return originalValue.orElse(null);
  }

  @JsonIgnore
  public Double getTotalDiscountValue() {
    return totalDiscountValue.orElse(null);
  }

  @JsonIgnore
  public Double getTotalAdditionalValue() {
    return totalAdditionalValue.orElse(null);
  }

  @JsonIgnore
  public Boolean getIsOverdue() {
    return isOverdue.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class BillSimulateBankSlipInfoResponseDtoBuilder {

    private JsonNullable<String> identificationField = JsonNullable.undefined();

    @JsonProperty("identificationField")
    public BillSimulateBankSlipInfoResponseDtoBuilder identificationField(String value) {
      this.identificationField = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public BillSimulateBankSlipInfoResponseDtoBuilder value(Double value) {
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dueDate = JsonNullable.undefined();

    @JsonProperty("dueDate")
    public BillSimulateBankSlipInfoResponseDtoBuilder dueDate(String value) {
      this.dueDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> companyName = JsonNullable.undefined();

    @JsonProperty("companyName")
    public BillSimulateBankSlipInfoResponseDtoBuilder companyName(String value) {
      this.companyName = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> bank = JsonNullable.undefined();

    @JsonProperty("bank")
    public BillSimulateBankSlipInfoResponseDtoBuilder bank(String value) {
      this.bank = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> beneficiaryCpfCnpj = JsonNullable.undefined();

    @JsonProperty("beneficiaryCpfCnpj")
    public BillSimulateBankSlipInfoResponseDtoBuilder beneficiaryCpfCnpj(String value) {
      this.beneficiaryCpfCnpj = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> beneficiaryName = JsonNullable.undefined();

    @JsonProperty("beneficiaryName")
    public BillSimulateBankSlipInfoResponseDtoBuilder beneficiaryName(String value) {
      this.beneficiaryName = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> allowChangeValue = JsonNullable.undefined();

    @JsonProperty("allowChangeValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder allowChangeValue(Boolean value) {
      this.allowChangeValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> minValue = JsonNullable.undefined();

    @JsonProperty("minValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder minValue(Double value) {
      this.minValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> maxValue = JsonNullable.undefined();

    @JsonProperty("maxValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder maxValue(Double value) {
      this.maxValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> discountValue = JsonNullable.undefined();

    @JsonProperty("discountValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder discountValue(Double value) {
      this.discountValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> interestValue = JsonNullable.undefined();

    @JsonProperty("interestValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder interestValue(Double value) {
      this.interestValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> fineValue = JsonNullable.undefined();

    @JsonProperty("fineValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder fineValue(Double value) {
      this.fineValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> originalValue = JsonNullable.undefined();

    @JsonProperty("originalValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder originalValue(Double value) {
      this.originalValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> totalDiscountValue = JsonNullable.undefined();

    @JsonProperty("totalDiscountValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder totalDiscountValue(Double value) {
      this.totalDiscountValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> totalAdditionalValue = JsonNullable.undefined();

    @JsonProperty("totalAdditionalValue")
    public BillSimulateBankSlipInfoResponseDtoBuilder totalAdditionalValue(Double value) {
      this.totalAdditionalValue = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> isOverdue = JsonNullable.undefined();

    @JsonProperty("isOverdue")
    public BillSimulateBankSlipInfoResponseDtoBuilder isOverdue(Boolean value) {
      this.isOverdue = JsonNullable.of(value);
      return this;
    }
  }
}
