// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ChargebackSaveDisputeRequestDto {

  /**
   * Files to create the dispute (Maximum: 11).
   */
  @NonNull
  private byte[] files;
}
