// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreditBureauReportGetResponseDto {

  /**
   * Unique report identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Date of consultation
   */
  @JsonProperty("dateCreated")
  private JsonNullable<String> dateCreated;

  /**
   * CPF or CNPJ consulted manually
   */
  @JsonProperty("cpfCnpj")
  private JsonNullable<String> cpfCnpj;

  /**
   * Unique customer identifier in Asaas
   */
  @JsonProperty("customer")
  private JsonNullable<String> customer;

  /**
   * Url to download the report. Available until 11:59 pm on the day of the appointment.
   */
  @JsonProperty("downloadUrl")
  private JsonNullable<String> downloadUrl;

  /**
   * PDF of the query report in Base64 (this field is only returned when the report is created)
   */
  @JsonProperty("reportFile")
  private JsonNullable<String> reportFile;

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public String getDateCreated() {
    return dateCreated.orElse(null);
  }

  @JsonIgnore
  public String getCpfCnpj() {
    return cpfCnpj.orElse(null);
  }

  @JsonIgnore
  public String getCustomer() {
    return customer.orElse(null);
  }

  @JsonIgnore
  public String getDownloadUrl() {
    return downloadUrl.orElse(null);
  }

  @JsonIgnore
  public String getReportFile() {
    return reportFile.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class CreditBureauReportGetResponseDtoBuilder {

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public CreditBureauReportGetResponseDtoBuilder id(String value) {
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dateCreated = JsonNullable.undefined();

    @JsonProperty("dateCreated")
    public CreditBureauReportGetResponseDtoBuilder dateCreated(String value) {
      this.dateCreated = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> cpfCnpj = JsonNullable.undefined();

    @JsonProperty("cpfCnpj")
    public CreditBureauReportGetResponseDtoBuilder cpfCnpj(String value) {
      this.cpfCnpj = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> customer = JsonNullable.undefined();

    @JsonProperty("customer")
    public CreditBureauReportGetResponseDtoBuilder customer(String value) {
      this.customer = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> downloadUrl = JsonNullable.undefined();

    @JsonProperty("downloadUrl")
    public CreditBureauReportGetResponseDtoBuilder downloadUrl(String value) {
      this.downloadUrl = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> reportFile = JsonNullable.undefined();

    @JsonProperty("reportFile")
    public CreditBureauReportGetResponseDtoBuilder reportFile(String value) {
      this.reportFile = JsonNullable.of(value);
      return this;
    }
  }
}
