// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * QrCode Format
 */
@Getter
@AllArgsConstructor
public enum Format {
  ALL("ALL"),
  IMAGE("IMAGE"),
  PAYLOAD("PAYLOAD");

  @JsonValue
  private final String value;

  @JsonCreator
  public static Format fromValue(String value) {
    return Arrays.stream(Format.values()).filter(item -> item.value.equals(value)).findFirst().orElse(null);
  }
}
