// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class GenerateSubscriptionBookletParameters {

  /**
   * Final month for generating the booklet
   */
  @JsonProperty("month")
  private JsonNullable<Long> month;

  /**
   * Final year for generating the booklet
   */
  @JsonProperty("year")
  private JsonNullable<Long> year;

  /**
   * Filter by column name
   */
  @JsonProperty("sort")
  private JsonNullable<String> sort;

  /**
   * Column ordering
   */
  @JsonProperty("order")
  private JsonNullable<String> order;

  @JsonIgnore
  public Long getMonth() {
    return month.orElse(null);
  }

  @JsonIgnore
  public Long getYear() {
    return year.orElse(null);
  }

  @JsonIgnore
  public String getSort() {
    return sort.orElse(null);
  }

  @JsonIgnore
  public String getOrder() {
    return order.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class GenerateSubscriptionBookletParametersBuilder {

    private JsonNullable<Long> month = JsonNullable.undefined();

    @JsonProperty("month")
    public GenerateSubscriptionBookletParametersBuilder month(Long value) {
      if (value == null) {
        throw new IllegalStateException("month cannot be null");
      }
      this.month = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> year = JsonNullable.undefined();

    @JsonProperty("year")
    public GenerateSubscriptionBookletParametersBuilder year(Long value) {
      if (value == null) {
        throw new IllegalStateException("year cannot be null");
      }
      this.year = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> sort = JsonNullable.undefined();

    @JsonProperty("sort")
    public GenerateSubscriptionBookletParametersBuilder sort(String value) {
      if (value == null) {
        throw new IllegalStateException("sort cannot be null");
      }
      this.sort = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> order = JsonNullable.undefined();

    @JsonProperty("order")
    public GenerateSubscriptionBookletParametersBuilder order(String value) {
      if (value == null) {
        throw new IllegalStateException("order cannot be null");
      }
      this.order = JsonNullable.of(value);
      return this;
    }
  }
}
