// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Transfer fees
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class MyAccountGetAccountFeesTransferDto {

  /**
   * Number of monthly free transactions
   */
  @JsonProperty("monthlyTransfersWithoutFee")
  private JsonNullable<Long> monthlyTransfersWithoutFee;

  /**
   * Fees for TED transfers
   */
  @JsonProperty("ted")
  private JsonNullable<MyAccountGetAccountFeesTransferTedDto> ted;

  /**
   * Fees for Pix transfers
   */
  @JsonProperty("pix")
  private JsonNullable<MyAccountGetAccountFeesTransferPixDto> pix;

  @JsonIgnore
  public Long getMonthlyTransfersWithoutFee() {
    return monthlyTransfersWithoutFee.orElse(null);
  }

  @JsonIgnore
  public MyAccountGetAccountFeesTransferTedDto getTed() {
    return ted.orElse(null);
  }

  @JsonIgnore
  public MyAccountGetAccountFeesTransferPixDto getPix() {
    return pix.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class MyAccountGetAccountFeesTransferDtoBuilder {

    private JsonNullable<Long> monthlyTransfersWithoutFee = JsonNullable.undefined();

    @JsonProperty("monthlyTransfersWithoutFee")
    public MyAccountGetAccountFeesTransferDtoBuilder monthlyTransfersWithoutFee(Long value) {
      this.monthlyTransfersWithoutFee = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<MyAccountGetAccountFeesTransferTedDto> ted = JsonNullable.undefined();

    @JsonProperty("ted")
    public MyAccountGetAccountFeesTransferDtoBuilder ted(MyAccountGetAccountFeesTransferTedDto value) {
      this.ted = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<MyAccountGetAccountFeesTransferPixDto> pix = JsonNullable.undefined();

    @JsonProperty("pix")
    public MyAccountGetAccountFeesTransferDtoBuilder pix(MyAccountGetAccountFeesTransferPixDto value) {
      this.pix = JsonNullable.of(value);
      return this;
    }
  }
}
