// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Kind of event
 */
@Getter
@AllArgsConstructor
public enum NotificationGetResponseNotificationEvent {
  PAYMENT_CREATED("PAYMENT_CREATED"),
  PAYMENT_UPDATED("PAYMENT_UPDATED"),
  PAYMENT_RECEIVED("PAYMENT_RECEIVED"),
  PAYMENT_OVERDUE("PAYMENT_OVERDUE"),
  PAYMENT_DUEDATE_WARNING("PAYMENT_DUEDATE_WARNING"),
  SEND_LINHA_DIGITAVEL("SEND_LINHA_DIGITAVEL");

  @JsonValue
  private final String value;

  @JsonCreator
  public static NotificationGetResponseNotificationEvent fromValue(String value) {
    return Arrays.stream(NotificationGetResponseNotificationEvent.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
