// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class PaymentLinkFileSaveRequestDto {

  /**
   * true to set as the main image
   */
  @JsonProperty("main")
  private JsonNullable<Boolean> main;

  /**
   * File
   */
  @JsonProperty("image")
  private JsonNullable<byte[]> image;

  @JsonIgnore
  public Boolean getMain() {
    return main.orElse(null);
  }

  @JsonIgnore
  public byte[] getImage() {
    return image.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class PaymentLinkFileSaveRequestDtoBuilder {

    private JsonNullable<Boolean> main = JsonNullable.undefined();

    @JsonProperty("main")
    public PaymentLinkFileSaveRequestDtoBuilder main(Boolean value) {
      this.main = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<byte[]> image = JsonNullable.undefined();

    @JsonProperty("image")
    public PaymentLinkFileSaveRequestDtoBuilder image(byte[] value) {
      if (value == null) {
        throw new IllegalStateException("image cannot be null");
      }
      this.image = JsonNullable.of(value);
      return this;
    }
  }
}
