// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class SubscriptionSaveWithCreditCardResponseDto {

  /**
   * Object type
   */
  @JsonProperty("object")
  private JsonNullable<String> object;

  /**
   * Unique subscription identifier in Asaas
   */
  @JsonProperty("id")
  private JsonNullable<String> id;

  /**
   * Subscription creation date
   */
  @JsonProperty("dateCreated")
  private JsonNullable<String> dateCreated;

  /**
   * Unique customer identifier
   */
  @JsonProperty("customer")
  private JsonNullable<String> customer;

  /**
   * Unique identifier of the payments link to which the subscription belongs
   */
  @JsonProperty("paymentLink")
  private JsonNullable<String> paymentLink;

  /**
   * Billing type
   */
  @JsonProperty("billingType")
  private JsonNullable<SubscriptionSaveWithCreditCardResponseBillingType> billingType;

  /**
   * Billing frequency
   */
  @JsonProperty("cycle")
  private JsonNullable<SubscriptionSaveWithCreditCardResponseCycle> cycle;

  /**
   * Subscription value
   */
  @JsonProperty("value")
  private JsonNullable<Double> value;

  /**
   * Due date of the next payment to be generated
   */
  @JsonProperty("nextDueDate")
  private JsonNullable<String> nextDueDate;

  /**
   * Deadline for payments to be due
   */
  @JsonProperty("endDate")
  private JsonNullable<String> endDate;

  /**
   * Subscription description
   */
  @JsonProperty("description")
  private JsonNullable<String> description;

  /**
   * Subscription status
   */
  @JsonProperty("status")
  private JsonNullable<SubscriptionSaveWithCreditCardResponseSubscriptionStatus> status;

  /**
   * Discount information
   */
  @JsonProperty("discount")
  private JsonNullable<PaymentDiscountDto> discount;

  /**
   * Fine information for payment after due date
   */
  @JsonProperty("fine")
  private JsonNullable<PaymentFineResponseDto> fine;

  /**
   * Interest information for payment after due date
   */
  @JsonProperty("interest")
  private JsonNullable<PaymentInterestResponseDto> interest;

  /**
   * Informs if the subscription has been removed
   */
  @JsonProperty("deleted")
  private JsonNullable<Boolean> deleted;

  /**
   * Maximum number of payments to be generated for this subscription
   */
  @JsonProperty("maxPayments")
  private JsonNullable<Long> maxPayments;

  /**
   * Subscription identifier on your system
   */
  @JsonProperty("externalReference")
  private JsonNullable<String> externalReference;

  /**
   * Unique checkout identifier
   */
  @JsonProperty("checkoutSession")
  private JsonNullable<String> checkoutSession;

  /**
   * Split information
   */
  @JsonProperty("split")
  private JsonNullable<List<SubscriptionSplitResponseDto>> split;

  /**
   * Credit card information
   */
  @JsonProperty("creditCard")
  private JsonNullable<PaymentSaveWithCreditCardCreditCardDto> creditCard;

  @JsonIgnore
  public String getObject() {
    return object.orElse(null);
  }

  @JsonIgnore
  public String getId() {
    return id.orElse(null);
  }

  @JsonIgnore
  public String getDateCreated() {
    return dateCreated.orElse(null);
  }

  @JsonIgnore
  public String getCustomer() {
    return customer.orElse(null);
  }

  @JsonIgnore
  public String getPaymentLink() {
    return paymentLink.orElse(null);
  }

  @JsonIgnore
  public SubscriptionSaveWithCreditCardResponseBillingType getBillingType() {
    return billingType.orElse(null);
  }

  @JsonIgnore
  public SubscriptionSaveWithCreditCardResponseCycle getCycle() {
    return cycle.orElse(null);
  }

  @JsonIgnore
  public Double getValue() {
    return value.orElse(null);
  }

  @JsonIgnore
  public String getNextDueDate() {
    return nextDueDate.orElse(null);
  }

  @JsonIgnore
  public String getEndDate() {
    return endDate.orElse(null);
  }

  @JsonIgnore
  public String getDescription() {
    return description.orElse(null);
  }

  @JsonIgnore
  public SubscriptionSaveWithCreditCardResponseSubscriptionStatus getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public PaymentDiscountDto getDiscount() {
    return discount.orElse(null);
  }

  @JsonIgnore
  public PaymentFineResponseDto getFine() {
    return fine.orElse(null);
  }

  @JsonIgnore
  public PaymentInterestResponseDto getInterest() {
    return interest.orElse(null);
  }

  @JsonIgnore
  public Boolean getDeleted() {
    return deleted.orElse(null);
  }

  @JsonIgnore
  public Long getMaxPayments() {
    return maxPayments.orElse(null);
  }

  @JsonIgnore
  public String getExternalReference() {
    return externalReference.orElse(null);
  }

  @JsonIgnore
  public String getCheckoutSession() {
    return checkoutSession.orElse(null);
  }

  @JsonIgnore
  public List<SubscriptionSplitResponseDto> getSplit() {
    return split.orElse(null);
  }

  @JsonIgnore
  public PaymentSaveWithCreditCardCreditCardDto getCreditCard() {
    return creditCard.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class SubscriptionSaveWithCreditCardResponseDtoBuilder {

    private JsonNullable<String> object = JsonNullable.undefined();

    @JsonProperty("object")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder object(String value) {
      this.object = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> id = JsonNullable.undefined();

    @JsonProperty("id")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder id(String value) {
      this.id = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> dateCreated = JsonNullable.undefined();

    @JsonProperty("dateCreated")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder dateCreated(String value) {
      this.dateCreated = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> customer = JsonNullable.undefined();

    @JsonProperty("customer")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder customer(String value) {
      this.customer = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> paymentLink = JsonNullable.undefined();

    @JsonProperty("paymentLink")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder paymentLink(String value) {
      this.paymentLink = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<SubscriptionSaveWithCreditCardResponseBillingType> billingType = JsonNullable.undefined();

    @JsonProperty("billingType")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder billingType(
      SubscriptionSaveWithCreditCardResponseBillingType value
    ) {
      this.billingType = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<SubscriptionSaveWithCreditCardResponseCycle> cycle = JsonNullable.undefined();

    @JsonProperty("cycle")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder cycle(SubscriptionSaveWithCreditCardResponseCycle value) {
      this.cycle = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Double> value = JsonNullable.undefined();

    @JsonProperty("value")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder value(Double value) {
      this.value = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> nextDueDate = JsonNullable.undefined();

    @JsonProperty("nextDueDate")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder nextDueDate(String value) {
      this.nextDueDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> endDate = JsonNullable.undefined();

    @JsonProperty("endDate")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder endDate(String value) {
      this.endDate = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> description = JsonNullable.undefined();

    @JsonProperty("description")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder description(String value) {
      this.description = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<SubscriptionSaveWithCreditCardResponseSubscriptionStatus> status = JsonNullable.undefined();

    @JsonProperty("status")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder status(
      SubscriptionSaveWithCreditCardResponseSubscriptionStatus value
    ) {
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<PaymentDiscountDto> discount = JsonNullable.undefined();

    @JsonProperty("discount")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder discount(PaymentDiscountDto value) {
      this.discount = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<PaymentFineResponseDto> fine = JsonNullable.undefined();

    @JsonProperty("fine")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder fine(PaymentFineResponseDto value) {
      this.fine = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<PaymentInterestResponseDto> interest = JsonNullable.undefined();

    @JsonProperty("interest")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder interest(PaymentInterestResponseDto value) {
      this.interest = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Boolean> deleted = JsonNullable.undefined();

    @JsonProperty("deleted")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder deleted(Boolean value) {
      this.deleted = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> maxPayments = JsonNullable.undefined();

    @JsonProperty("maxPayments")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder maxPayments(Long value) {
      this.maxPayments = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> externalReference = JsonNullable.undefined();

    @JsonProperty("externalReference")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder externalReference(String value) {
      this.externalReference = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> checkoutSession = JsonNullable.undefined();

    @JsonProperty("checkoutSession")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder checkoutSession(String value) {
      this.checkoutSession = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<List<SubscriptionSplitResponseDto>> split = JsonNullable.undefined();

    @JsonProperty("split")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder split(List<SubscriptionSplitResponseDto> value) {
      this.split = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<PaymentSaveWithCreditCardCreditCardDto> creditCard = JsonNullable.undefined();

    @JsonProperty("creditCard")
    public SubscriptionSaveWithCreditCardResponseDtoBuilder creditCard(PaymentSaveWithCreditCardCreditCardDto value) {
      this.creditCard = JsonNullable.of(value);
      return this;
    }
  }
}
