// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Filter by billing type
 */
@Getter
@AllArgsConstructor
public enum SubscriptionListRequestBillingType {
  UNDEFINED("UNDEFINED"),
  BOLETO("BOLETO"),
  CREDIT_CARD("CREDIT_CARD"),
  DEBIT_CARD("DEBIT_CARD"),
  TRANSFER("TRANSFER"),
  DEPOSIT("DEPOSIT"),
  PIX("PIX");

  @JsonValue
  private final String value;

  @JsonCreator
  public static SubscriptionListRequestBillingType fromValue(String value) {
    return Arrays.stream(SubscriptionListRequestBillingType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
