// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Account type
 */
@Getter
@AllArgsConstructor
public enum TransferBankAccountSaveRequestBankAccountType {
  CONTA_CORRENTE("CONTA_CORRENTE"),
  CONTA_POUPANCA("CONTA_POUPANCA");

  @JsonValue
  private final String value;

  @JsonCreator
  public static TransferBankAccountSaveRequestBankAccountType fromValue(String value) {
    return Arrays.stream(TransferBankAccountSaveRequestBankAccountType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
