// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.validation.validators;

import com.asaas.sdk.asaasjavasdk.validation.Violation;

public interface Validator<T> {
  Violation[] validate(T value);
}
