// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.exceptions;

import com.asaas.sdk.asaasjavasdk.models.ApiErrorResponseDtoModel;
import lombok.Getter;
import okhttp3.Response;

/**
 * Exception class for ApiErrorResponseDto errors.
 */
@Getter
public class ApiErrorResponseDto extends ApiError {

  private final ApiErrorResponseDtoModel error;

  public ApiErrorResponseDto(ApiErrorResponseDtoModel error, String message, int code, Response response) {
    super(message, code, response);
    this.error = error;
  }
}
