// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.exceptions;

import com.asaas.sdk.asaasjavasdk.models.ApiErrorResponseDto;
import lombok.Getter;
import okhttp3.Response;

/**
 * Exception class for ApiErrorResponseDto errors.
 */
@Getter
public class ApiErrorResponseDtoException extends ApiError {

  private final ApiErrorResponseDto error;

  public ApiErrorResponseDtoException(ApiErrorResponseDto error, String message, int code, Response response) {
    super(message, code, response);
    this.error = error;
  }
}
