// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.validation.validators.modelValidators;

import com.asaas.sdk.asaasjavasdk.models.CreateNewCheckoutRequest;
import com.asaas.sdk.asaasjavasdk.validation.Violation;
import com.asaas.sdk.asaasjavasdk.validation.ViolationAggregator;
import com.asaas.sdk.asaasjavasdk.validation.validators.NumericValidator;

public class CreateNewCheckoutRequestValidator extends AbstractModelValidator<CreateNewCheckoutRequest> {

  public CreateNewCheckoutRequestValidator(String fieldName) {
    super(fieldName);
  }

  public CreateNewCheckoutRequestValidator() {}

  @Override
  protected Violation[] validateModel(CreateNewCheckoutRequest createNewCheckoutRequest) {
    return new ViolationAggregator()
      .add(
        new NumericValidator<Long>("minutesToExpire")
          .min(10L)
          .max(1440L)
          .optional()
          .validate(createNewCheckoutRequest.getMinutesToExpire())
      )
      .add(
        new ApiCheckoutSessionInstallmentDtoValidator("installment")
          .optional()
          .validate(createNewCheckoutRequest.getInstallment())
      )
      .aggregate();
  }
}
