// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.validation.validators.modelValidators;

import com.asaas.sdk.asaasjavasdk.models.ListPaymentsParameters;
import com.asaas.sdk.asaasjavasdk.validation.Violation;
import com.asaas.sdk.asaasjavasdk.validation.ViolationAggregator;
import com.asaas.sdk.asaasjavasdk.validation.validators.NumericValidator;

public class ListPaymentsParametersValidator extends AbstractModelValidator<ListPaymentsParameters> {

  public ListPaymentsParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListPaymentsParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListPaymentsParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
