// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.validation.validators.modelValidators;

import com.asaas.sdk.asaasjavasdk.models.ListNbsCodesParameters;
import com.asaas.sdk.asaasjavasdk.validation.Violation;
import com.asaas.sdk.asaasjavasdk.validation.ViolationAggregator;
import com.asaas.sdk.asaasjavasdk.validation.validators.NumericValidator;

public class ListNbsCodesParametersValidator extends AbstractModelValidator<ListNbsCodesParameters> {

  public ListNbsCodesParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListNbsCodesParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListNbsCodesParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
