// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.validation.validators.modelValidators;

import com.asaas.sdk.asaasjavasdk.models.ListInstallmentsParameters;
import com.asaas.sdk.asaasjavasdk.validation.Violation;
import com.asaas.sdk.asaasjavasdk.validation.ViolationAggregator;
import com.asaas.sdk.asaasjavasdk.validation.validators.NumericValidator;

public class ListInstallmentsParametersValidator extends AbstractModelValidator<ListInstallmentsParameters> {

  public ListInstallmentsParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListInstallmentsParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListInstallmentsParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
