// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.services;

import com.asaas.apisdk.config.AsaasSdkConfig;
import com.asaas.apisdk.exceptions.ApiError;
import com.asaas.apisdk.exceptions.ApiErrorResponseDtoException;
import com.asaas.apisdk.http.Environment;
import com.asaas.apisdk.http.HttpMethod;
import com.asaas.apisdk.http.ModelConverter;
import com.asaas.apisdk.http.util.RequestBuilder;
import com.asaas.apisdk.models.ApiErrorResponseDto;
import com.asaas.apisdk.models.ApiPaymentBankSlipRefundResponseDto;
import com.asaas.apisdk.models.ApiPaymentRefundListResponseDto;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import lombok.NonNull;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/**
 * PaymentRefundService Service
 */
public class PaymentRefundService extends BaseService {

  public PaymentRefundService(@NonNull OkHttpClient httpClient, AsaasSdkConfig config) {
    super(httpClient, config);
  }

  /**
   * Retrieve refunds of a single payment
   *
   * @param id String Unique payment identifier in Asaas
   * @return response of {@code ApiPaymentRefundListResponseDto}
   */
  public ApiPaymentRefundListResponseDto retrieveRefundsOfASinglePayment(@NonNull String id) throws ApiError {
    this.addErrorMapping(400, ApiErrorResponseDto.class, ApiErrorResponseDtoException.class);
    Request request = this.buildRetrieveRefundsOfASinglePaymentRequest(id);
    Response response = this.execute(request);
    return ModelConverter.convert(response, new TypeReference<ApiPaymentRefundListResponseDto>() {});
  }

  /**
   * Retrieve refunds of a single payment
   *
   * @param id String Unique payment identifier in Asaas
   * @return response of {@code CompletableFuture<ApiPaymentRefundListResponseDto>}
   */
  public CompletableFuture<ApiPaymentRefundListResponseDto> retrieveRefundsOfASinglePaymentAsync(@NonNull String id)
    throws ApiError {
    this.addErrorMapping(400, ApiErrorResponseDto.class, ApiErrorResponseDtoException.class);
    Request request = this.buildRetrieveRefundsOfASinglePaymentRequest(id);
    CompletableFuture<Response> futureResponse = this.executeAsync(request);
    return futureResponse.thenApplyAsync(response ->
      ModelConverter.convert(response, new TypeReference<ApiPaymentRefundListResponseDto>() {})
    );
  }

  private Request buildRetrieveRefundsOfASinglePaymentRequest(@NonNull String id) {
    return new RequestBuilder(
      HttpMethod.GET,
      Optional.ofNullable(this.config.getBaseUrl()).orElse(Environment.DEFAULT.getUrl()),
      "v3/payments/{id}/refunds"
    )
      .setApiKeyAuth(this.config.getApiKeyAuthConfig())
      .setPathParameter("id", id)
      .build();
  }

  /**
   * Refund Bank Slip
   *
   * @param id String Unique payment identifier in Asaas
   * @param input Object Request Body
   * @return response of {@code ApiPaymentBankSlipRefundResponseDto}
   */
  public ApiPaymentBankSlipRefundResponseDto refundBankSlip(@NonNull String id, @NonNull Object input) throws ApiError {
    this.addErrorMapping(400, ApiErrorResponseDto.class, ApiErrorResponseDtoException.class);
    Request request = this.buildRefundBankSlipRequest(id, input);
    Response response = this.execute(request);
    return ModelConverter.convert(response, new TypeReference<ApiPaymentBankSlipRefundResponseDto>() {});
  }

  /**
   * Refund Bank Slip
   *
   * @param id String Unique payment identifier in Asaas
   * @param input Object Request Body
   * @return response of {@code CompletableFuture<ApiPaymentBankSlipRefundResponseDto>}
   */
  public CompletableFuture<ApiPaymentBankSlipRefundResponseDto> refundBankSlipAsync(
    @NonNull String id,
    @NonNull Object input
  ) throws ApiError {
    this.addErrorMapping(400, ApiErrorResponseDto.class, ApiErrorResponseDtoException.class);
    Request request = this.buildRefundBankSlipRequest(id, input);
    CompletableFuture<Response> futureResponse = this.executeAsync(request);
    return futureResponse.thenApplyAsync(response ->
      ModelConverter.convert(response, new TypeReference<ApiPaymentBankSlipRefundResponseDto>() {})
    );
  }

  private Request buildRefundBankSlipRequest(@NonNull String id, @NonNull Object input) {
    return new RequestBuilder(
      HttpMethod.POST,
      Optional.ofNullable(this.config.getBaseUrl()).orElse(Environment.DEFAULT.getUrl()),
      "v3/payments/{id}/bankSlip/refund"
    )
      .setApiKeyAuth(this.config.getApiKeyAuthConfig())
      .setPathParameter("id", id)
      .setJsonContent(input)
      .build();
  }
}
