// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCheckoutSessionResponseDto {

  /**
   * Payment methods
   */
  private List<String> billingTypes;

  /**
   * Charge types
   */
  private List<String> chargeTypes;

  /**
   * Time in minutes for checkout expiration
   */
  private Long minutesToExpire;

  private ApiCheckoutSessionCallbackDto callback;

  /**
   * List of items at checkout
   */
  private List<ApiCheckoutSessionItemsDto> items;

  private ApiCheckoutSessionCustomerDataDto customerData;

  private ApiCheckoutSessionSubscriptionDto subscription;

  private ApiCheckoutSessionInstallmentDto installment;

  /**
   * Split Settings
   */
  private List<ApiCheckoutSessionSplitDto> split;
}
