// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCreditCardHolderInfoRequestDto {

  /**
   * Name of card holder
   */
  @NonNull
  private String name;

  /**
   * Cardholder email
   */
  @NonNull
  private String email;

  /**
   * CPF or CNPJ of the cardholder
   */
  @NonNull
  private String cpfCnpj;

  /**
   * Cardholder zip code
   */
  @NonNull
  private String postalCode;

  /**
   * Cardholder address number
   */
  @NonNull
  private String addressNumber;

  /**
   * Phone with cardholder's area code
   */
  @NonNull
  private String phone;

  /**
   * Supplementing the cardholder's address
   */
  private String addressComplement;

  /**
   * Cardholder's cell phone
   */
  private String mobilePhone;
}
