// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCustomerFiscalInfoGetResponseDto {

  /**
   * Object type
   */
  private String object;

  /**
   * Email used by Asaas to send invoice notifications and alerts
   */
  private String email;

  /**
   * Company municipal registration
   */
  private String municipalInscription;

  /**
   * Indicates whether the company opts for the simple national system
   */
  @Builder.Default
  private Boolean simplesNacional = true;

  /**
   * Identifies whether the company is classified as a cultural promoter
   */
  @Builder.Default
  private Boolean culturalProjectsPromoter = true;

  /**
   * CNAE code
   */
  private String cnae;

  /**
   * Special taxation regime identifier
   */
  private String specialTaxRegime;

  /**
   * Service list item, as http://www.planalto.gov.br/ccivil_03/leis/LCP/Lcp116.htm
   */
  private String serviceListItem;

  /**
   * NBS Code (Brazilian Nomenclature of Services). It must be included on the NFS-e (Electronic Service Invoice) when required by the municipal government and/or for import or export services. Check with your local government or your accounting department to determine whether this information is necessary.
   */
  private String nbsCode;

  /**
   * Serial Number registered for the company
   */
  private String rpsSerie;

  /**
   * RPS number used in the last invoice issued to your company
   */
  private Long rpsNumber;

  /**
   * Batch number used on the last invoice issued by your company
   */
  private Long loteNumber;

  /**
   * User to access your city's city hall website
   */
  private String username;

  /**
   * Indicates whether the password to access the city hall website has been entered
   */
  @Builder.Default
  private Boolean passwordSent = true;

  /**
   * Indicates whether the token for accessing the city hall website was provided
   */
  @Builder.Default
  private Boolean accessTokenSent = true;

  /**
   * Indicates whether the digital certificate for access to the city hall website has been provided
   */
  @Builder.Default
  private Boolean certificateSent = true;

  /**
   * Identifier of the tax calculation regime
   */
  private String nationalPortalTaxCalculationRegime;
}
