// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCustomerSaveOrUpdatePaymentCustodyConfigRequestDto {

  /**
   * Number of days to expire the payment escrow
   */
  @NonNull
  private Long daysToExpire;

  /**
   * Indicates whether the Escrow Account is enabled
   */
  private Boolean enabled;

  /**
   * Indicates whether the subaccount is responsible for paying the Escrow Account fee. If not informed, the main account will be responsible for the fee
   */
  private Boolean isFeePayer;

  /**
   * Unique subaccount identifier in Asaas
   */
  private String id;
}
