// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Filter by situation
 */
@Getter
@AllArgsConstructor
public enum ApiCustomerInvoiceListRequestInvoiceStatus {
  SCHEDULED("SCHEDULED"),
  AUTHORIZED("AUTHORIZED"),
  PROCESSING_CANCELLATION("PROCESSING_CANCELLATION"),
  CANCELED("CANCELED"),
  CANCELLATION_DENIED("CANCELLATION_DENIED"),
  ERROR("ERROR");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiCustomerInvoiceListRequestInvoiceStatus fromValue(String value) {
    return Arrays.stream(ApiCustomerInvoiceListRequestInvoiceStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
