// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Person Type
 */
@Getter
@AllArgsConstructor
public enum ApiCustomerUpdateRequestSaveRequestPersonType {
  JURIDICA("JURIDICA"),
  FISICA("FISICA");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiCustomerUpdateRequestSaveRequestPersonType fromValue(String value) {
    return Arrays.stream(ApiCustomerUpdateRequestSaveRequestPersonType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
