// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiCustomerUpdateRequestCityDto {

  /**
   * Object type
   */
  private String object;

  /**
   * Unique city identifier in Asaas
   */
  private Long id;

  /**
   * IBGE Code
   */
  private String ibgeCode;

  /**
   * City's name
   */
  private String name;

  /**
   * District code
   */
  private String districtCode;

  /**
   * District name
   */
  private String district;

  /**
   * State abbreviation (SP, RJ, SC, ...)
   */
  private ApiCustomerUpdateRequestCityState state;
}
