// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiInstallmentSplitRequestDto {

  /**
   * Asaas wallet identifier that will be transferred
   */
  @NonNull
  private String walletId;

  /**
   * Fixed amount to be transferred to the account when the payment is received
   */
  private Double fixedValue;

  /**
   * Percentage of the net value of the charge to be transferred when received
   */
  private Double percentualValue;

  /**
   * (Instalments only). Amount that will be split relative to the total amount that will be paid in installments.
   */
  private Double totalFixedValue;

  /**
   * Split identifier in your system
   */
  private String externalReference;

  /**
   * Split description
   */
  private String description;

  /**
   * Installment number to which the split will be linked. Cannot be provided along with the 'totalFixedValue' field
   */
  private Long installmentNumber;
}
