// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPixTransactionQrCodePayerResponseDto {

  /**
   * Payer's name
   */
  private String name;

  /**
   * CPF or CNPJ of the payer
   */
  private String cpfCnpj;
}
