// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentDiscountDto {

  /**
   * Percentage or fixed amount of discount to be applied to the Payment amount
   */
  private Double value;

  /**
   * Days before expiration to apply discount. Ex: 0 = until expiration, 1 = up to one day before, 2 = up to 2 days before, and so on
   */
  private Long dueDateLimitDays;

  /**
   * Discount type
   */
  private ApiPaymentDiscountDiscountType type;
}
