// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Payment escrow status
 */
@Getter
@AllArgsConstructor
public enum ApiPaymentCustodyGetResponsePaymentCustodyStatus {
  ACTIVE("ACTIVE"),
  DONE("DONE");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiPaymentCustodyGetResponsePaymentCustodyStatus fromValue(String value) {
    return Arrays.stream(ApiPaymentCustodyGetResponsePaymentCustodyStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
