// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

/**
 * Credit card information
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPaymentSaveWithCreditCardCreditCardDto {

  /**
   * Last 4 digits of the card used
   */
  private String creditCardNumber;

  /**
   * Flag of the card used
   */
  private ApiPaymentSaveWithCreditCardCreditCardCreditCardBrand creditCardBrand;

  /**
   * Credit card token if tokenization is active.
   */
  private String creditCardToken;
}
