// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPixOriginalTransactionResponseDto {

  /**
   * Unique transaction identifier
   */
  private String id;

  /**
   * Unique identifier of the Pix transaction at the Central Bank
   */
  private String endToEndIdentifier;

  /**
   * Original transaction value
   */
  private Double value;

  /**
   * Transaction date
   */
  private String effectiveDate;
}
