// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Filter by current key status
 */
@Getter
@AllArgsConstructor
public enum ApiPixAddressKeyListRequestPixAddressKeyStatus {
  AWAITING_ACTIVATION("AWAITING_ACTIVATION"),
  ACTIVE("ACTIVE"),
  AWAITING_DELETION("AWAITING_DELETION"),
  AWAITING_ACCOUNT_DELETION("AWAITING_ACCOUNT_DELETION"),
  DELETED("DELETED"),
  ERROR("ERROR");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiPixAddressKeyListRequestPixAddressKeyStatus fromValue(String value) {
    return Arrays.stream(ApiPixAddressKeyListRequestPixAddressKeyStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
