// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Recurrence item status
 */
@Getter
@AllArgsConstructor
public enum ApiPixTransactionRecurringCheckoutScheduleGetItemResponseRecurringCheckoutSchedulePixItemStatus {
  PENDING("PENDING"),
  CANCELLED("CANCELLED"),
  REFUSED("REFUSED"),
  DONE("DONE");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiPixTransactionRecurringCheckoutScheduleGetItemResponseRecurringCheckoutSchedulePixItemStatus fromValue(
    String value
  ) {
    return Arrays.stream(
      ApiPixTransactionRecurringCheckoutScheduleGetItemResponseRecurringCheckoutSchedulePixItemStatus.values()
    )
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
