// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Indicates the origin of the recurrence
 */
@Getter
@AllArgsConstructor
public enum ApiPixTransactionRecurringCheckoutScheduleGetResponseRecurringCheckoutScheduleOrigin {
  PIX("PIX");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiPixTransactionRecurringCheckoutScheduleGetResponseRecurringCheckoutScheduleOrigin fromValue(
    String value
  ) {
    return Arrays.stream(ApiPixTransactionRecurringCheckoutScheduleGetResponseRecurringCheckoutScheduleOrigin.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
