// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Payment billing type
 */
@Getter
@AllArgsConstructor
public enum ApiPaymentSaveRequestBillingType {
  UNDEFINED("UNDEFINED"),
  BOLETO("BOLETO"),
  CREDIT_CARD("CREDIT_CARD"),
  PIX("PIX");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiPaymentSaveRequestBillingType fromValue(String value) {
    return Arrays.stream(ApiPaymentSaveRequestBillingType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
