// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiPixQrCodeDecodeResponseDto {

  /**
   * Copy and Paste of the QRCode
   */
  private String payload;

  /**
   * QRCode Type
   */
  private ApiPixQrCodeDecodeResponsePixQrCodeType type;

  /**
   * Transaction origin
   */
  private ApiPixQrCodeDecodeResponsePixTransactionOriginType transactionOriginType;

  /**
   * Pix key used
   */
  private String pixKey;

  /**
   * Unique Pix reconciliation identifier with Asaas
   */
  private String conciliationIdentifier;

  /**
   * Due date
   */
  private String dueDate;

  /**
   * Expiration date
   */
  private String expirationDate;

  /**
   * Used to indicate whether it is a Withdrawal or Change
   */
  private ApiPixQrCodeDecodeResponsePixTransactionCashValueFinality finality;

  /**
   * QRCode Value
   */
  private Double value;

  /**
   * Change value
   */
  private Double changeValue;

  /**
   * Interest value
   */
  private Double interest;

  /**
   * Fine value
   */
  private Double fine;

  /**
   * Discount value
   */
  private Double discount;

  /**
   * Total amount with fine, interest and discount applied
   */
  private Double totalValue;

  /**
   * Informs if the QRCode can be paid with another amount
   */
  private Boolean canBePaidWithDifferentValue;

  /**
   * Informs whether the change can be paid with another amount
   */
  private Boolean canBeModifyChangeValue;

  private ApiPixQrCodeDecodeReceiverDto receiver;

  private ApiPixTransactionQrCodePayerResponseDto payer;

  /**
   * Description provided during the creation of the QRCode
   */
  private String description;

  /**
   * Informs if the QRCode can be paid
   */
  private Boolean canBePaid;

  /**
   * Informs why QRCode cannot be paid
   */
  private String cannotBePaidReason;
}
