// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * When the invoice will be issued
 */
@Getter
@AllArgsConstructor
public enum ApiSubscriptionConfigureInvoiceRequestDtoEffectiveDatePeriod {
  ON_PAYMENT_CONFIRMATION("ON_PAYMENT_CONFIRMATION"),
  ON_PAYMENT_DUE_DATE("ON_PAYMENT_DUE_DATE"),
  BEFORE_PAYMENT_DUE_DATE("BEFORE_PAYMENT_DUE_DATE"),
  ON_DUE_DATE_MONTH("ON_DUE_DATE_MONTH"),
  ON_NEXT_MONTH("ON_NEXT_MONTH");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiSubscriptionConfigureInvoiceRequestDtoEffectiveDatePeriod fromValue(String value) {
    return Arrays.stream(ApiSubscriptionConfigureInvoiceRequestDtoEffectiveDatePeriod.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
