// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

/**
 * Bank account details
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiTransferBankAccountGetResponseDto {

  /**
   * Bank account name
   */
  private ApiTransferBankGetResponseDto bank;

  /**
   * Name of bank account owner
   */
  private String accountName;

  /**
   * Name of bank account owner
   */
  private String ownerName;

  /**
   * CPF or CNPJ of the bank account owner
   */
  private String cpfCnpj;

  /**
   * Non-digit agency number
   */
  private String agency;

  /**
   * Agency digit
   */
  private String agencyDigit;

  /**
   * Non-digit bank account number
   */
  private String account;

  /**
   * Bank account digit
   */
  private String accountDigit;

  /**
   * Pix key address
   */
  private String pixAddressKey;
}
