// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

/**
 * Recurrence information. Only for Pix transfers
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ApiTransferRecurringSaveRequestDto {

  /**
   * Frequency
   */
  private ApiTransferRecurringSaveRequestRecurringCheckoutScheduleFrequency frequency;

  /**
   * Number of repetitions. This transfer will be included as the first transaction of the recurrence.
   * For the `WEEKLY` frequency, the maximum accepted is: `51`
   * For the `MONTHLY` frequency, the maximum accepted is: `11`
   */
  private Long quantity;
}
