// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Transfer status
 */
@Getter
@AllArgsConstructor
public enum ApiTransferSaveInternalTransferResponseTransferStatus {
  PENDING("PENDING"),
  BANK_PROCESSING("BANK_PROCESSING"),
  DONE("DONE"),
  CANCELLED("CANCELLED"),
  FAILED("FAILED");

  @JsonValue
  private final String value;

  @JsonCreator
  public static ApiTransferSaveInternalTransferResponseTransferStatus fromValue(String value) {
    return Arrays.stream(ApiTransferSaveInternalTransferResponseTransferStatus.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
