// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Invoice type
 */
@Getter
@AllArgsConstructor
public enum CancelAnInvoiceOkResponseType {
  NFS_E("NFS-e");

  @JsonValue
  private final String value;

  @JsonCreator
  public static CancelAnInvoiceOkResponseType fromValue(String value) {
    return Arrays.stream(CancelAnInvoiceOkResponseType.values())
      .filter(item -> item.value.equals(value))
      .findFirst()
      .orElse(null);
  }
}
