// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CheckPendingDocumentsOkResponseData {

  /**
   * Unique document group identifier in Asaas
   */
  private String id;

  /**
   * Document group status
   */
  private ApiAccountDocumentGroupResponseCustomerDocumentStatus status;

  /**
   * Type of documents
   */
  private ApiAccountDocumentGroupResponseCustomerDocumentType type;

  /**
   * Document group title
   */
  private String title;

  /**
   * Description
   */
  private String description;

  /**
   * Who is responsible for sending these documents
   */
  private ApiAccountDocumentGroupResponsibleResponseDto responsible;

  /**
   * URL for sending documents
   */
  private String onboardingUrl;

  /**
   * Expiration date of the URL for sending documents
   */
  private String onboardingUrlExpirationDate;

  /**
   * Documents that have already been sent with their respective identifiers
   */
  private List<ApiAccountDocumentGetResponseDto> documents;
}
