// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateStaticQrcodeRequest {

  /**
   * Key that will receive QrCode payments
   */
  private String addressKey;

  /**
   * QrCode Description
   */
  private String description;

  /**
   * Value of the QrCode, if not informed, the payer can choose the value
   */
  private Double value;

  /**
   * QrCode Format
   */
  private Format format;

  /**
   * QrCode expiration date/time, after this date all payments will be refused.
   */
  private String expirationDate;

  /**
   * Determines the expiration date in seconds.
   */
  private Long expirationSeconds;

  /**
   * Defines whether the QrCode can be paid multiple times, if not entered the default value is true.
   */
  private Boolean allowsMultiplePayments;

  /**
   * Free search field
   */
  private String externalReference;
}
