// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateInstallmentWithCreditCardRequest {

  /**
   * Number of installments
   */
  @NonNull
  private Long installmentCount;

  /**
   * Unique customer identifier in Asaas
   */
  @NonNull
  private String customer;

  /**
   * Value of each installment
   */
  @NonNull
  private Double value;

  /**
   * Payment billing type
   */
  @NonNull
  private ApiInstallmentSaveWithCreditCardRequestBillingType billingType;

  /**
   * Due date of the first installment
   */
  @NonNull
  private String dueDate;

  /**
   * Credit card information
   */
  @NonNull
  private ApiCreditCardRequestDto creditCard;

  /**
   * Credit card holder information
   */
  @NonNull
  private ApiCreditCardHolderInfoRequestDto creditCardHolderInfo;

  /**
   * IP from where the customer is making the purchase. Your server's IP must not be entered.
   */
  @NonNull
  private String remoteIp;

  /**
   * Total installment amount
   */
  private Double totalValue;

  /**
   * Installment description (max. 500 characters)
   */
  private String description;

  /**
   * Define whether the payment will be sent via post
   */
  private Boolean postalService;

  /**
   * Days after registration cancellation deadline (only for bank slip)
   */
  private Long daysAfterDueDateToRegistrationCancellation;

  /**
   * Free search field
   */
  private String paymentExternalReference;

  /**
   * Discount information
   */
  private ApiPaymentDiscountDto discount;

  /**
   * Interest information for payment after due date
   */
  private ApiPaymentInterestRequestDto interest;

  /**
   * Fine information for payment after due date
   */
  private ApiPaymentFineRequestDto fine;

  /**
   * Split Settings
   */
  private List<ApiInstallmentSplitRequestDto> splits;

  /**
   * Credit card token for using the credit card tokenization functionality. If informed, the fields creditCard and creditCardHolderInfo are not mandatory.
   */
  private String creditCardToken;

  /**
   * Carry out only the Pre-Authorization of the installment
   */
  private Boolean authorizeOnly;
}
