// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateAPaymentDunningRequest {

  /**
   * Unique identifier of the payment to be recovered in Asaas
   */
  @NonNull
  private String payment;

  /**
   * Type of payment dunning
   */
  @NonNull
  private ApiPaymentDunningSaveRequestPaymentDunningType type;

  /**
   * Client name
   */
  @NonNull
  private String customerName;

  /**
   * Customer CPF or CNPJ
   */
  @NonNull
  private String customerCpfCnpj;

  /**
   * Customer main telephone number
   */
  @NonNull
  private String customerPrimaryPhone;

  /**
   * Customer address zip code
   */
  @NonNull
  private String customerPostalCode;

  /**
   * Customer public address
   */
  @NonNull
  private String customerAddress;

  /**
   * Customer address number
   */
  @NonNull
  private String customerAddressNumber;

  /**
   * Customer neighborhood
   */
  @NonNull
  private String customerProvince;

  /**
   * Description of the product or service provided
   */
  private String description;

  /**
   * Secondary customer phone number
   */
  private String customerSecondaryPhone;

  /**
   * Customer address complement
   */
  private String customerComplement;

  /**
   * Invoice and/or contract notarized
   */
  private byte[] documents;
}
