// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateNewSubscriptionRequestSplit {

  /**
   * Asaas wallet identifier that will be transferred
   */
  @NonNull
  private String walletId;

  /**
   * Fixed amount to be transferred to the account when the payment is received
   */
  private Double fixedValue;

  /**
   * Percentage of the net value of the charge to be transferred when received
   */
  private Double percentualValue;

  /**
   * Split identifier in your system
   */
  private String externalReference;

  /**
   * Split description
   */
  private String description;
}
