// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import java.util.List;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class CreateSubscriptionWithCreditCardRequest {

  /**
   * Unique customer identifier in Asaas
   */
  @NonNull
  private String customer;

  /**
   * Billing type
   */
  @NonNull
  private ApiSubscriptionSaveWithCreditCardRequestBillingType billingType;

  /**
   * Subscription value
   */
  @NonNull
  private Double value;

  /**
   * First payment due
   */
  @NonNull
  private String nextDueDate;

  /**
   * Billing frequency
   */
  @NonNull
  private ApiSubscriptionSaveWithCreditCardRequestCycle cycle;

  /**
   * Credit card information
   */
  @NonNull
  private ApiCreditCardRequestDto creditCard;

  /**
   * Credit card holder information
   */
  @NonNull
  private ApiCreditCardHolderInfoRequestDto creditCardHolderInfo;

  /**
   * IP from where the customer is making the purchase. Your server's IP must not be entered.
   */
  @NonNull
  private String remoteIp;

  /**
   * Discount information
   */
  private ApiPaymentDiscountDto discount;

  /**
   * Interest information for payment after due date
   */
  private ApiPaymentInterestRequestDto interest;

  /**
   * Fine information for payment after due date
   */
  private ApiPaymentFineRequestDto fine;

  /**
   * Subscription description (max. 500 characters)
   */
  private String description;

  /**
   * Deadline for payments to be due
   */
  private String endDate;

  /**
   * Maximum number of payments to be generated for this subscription
   */
  private Long maxPayments;

  /**
   * Subscription identifier on your system
   */
  private String externalReference;

  /**
   * Split information
   */
  private List<ApiSubscriptionSplitRequestDto> split;

  /**
   * Automatic redirection information after the payment of the link payment
   */
  private ApiPaymentCallbackRequestDto callback;

  /**
   * Credit card token for using the credit card tokenization functionality. If informed, the fields above are not mandatory.
   */
  private String creditCardToken;
}
