// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ListTransactionsParameters {

  /**
   * List starting element
   */
  private Long offset;

  /**
   * Number of list elements (max: 100)
   */
  private Long limit;

  /**
   * Filter by transaction status
   */
  private ApiPixTransactionListRequestPixTransactionStatus status;

  /**
   * Filter by transaction type
   */
  private ApiPixTransactionListRequestPixTransactionType type;

  /**
   * Filter by Pix transaction identifier at the Central Bank
   */
  private String endToEndIdentifier;
}
