// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ListSubscriptionsParameters {

  /**
   * List starting element
   */
  private Long offset;

  /**
   * Number of list elements (max: 100)
   */
  private Long limit;

  /**
   * Filter by Unique Customer Identifier
   */
  private String customer;

  /**
   * Filter by customer group name
   */
  private String customerGroupName;

  /**
   * Filter by billing type
   */
  private ApiSubscriptionListRequestBillingType billingType;

  /**
   * Filter by status
   */
  private ApiSubscriptionListRequestSubscriptionStatus status;

  /**
   * Send true to return only removed subscriptions
   */
  private String deletedOnly;

  /**
   * Send true to also recover removed subscriptions
   */
  private String includeDeleted;

  /**
   * Filter by your system identifier
   */
  private String externalReference;

  /**
   * Ascending or descending order
   */
  private String order;

  /**
   * Which field will it be sorted by
   */
  private String sort;
}
