// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class ListPaymentsLinksParameters {

  /**
   * List starting element
   */
  private Long offset;

  /**
   * Number of list elements (max: 100)
   */
  private Long limit;

  /**
   * Filter by activated or deactivated payment link
   */
  private Boolean active;

  /**
   * True to also retrieve removed payment links
   */
  private Boolean includeDeleted;

  /**
   * Filter by payments link name
   */
  private String name;

  /**
   * Filter by your system identifier
   */
  private String externalReference;
}
