// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class RemoveSentDocumentOkResponse {

  /**
   * Indicates whether the document was removed
   */
  private Boolean deleted;

  /**
   * Unique document identifier in Asaas
   */
  private String id;
}
