// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class RetrieveACreditBureauReportOkResponse {

  /**
   * Unique report identifier in Asaas
   */
  private String id;

  /**
   * Date of consultation
   */
  private String dateCreated;

  /**
   * CPF or CNPJ consulted manually
   */
  private String cpfCnpj;

  /**
   * Unique customer identifier in Asaas
   */
  private String customer;

  /**
   * Url to download the report. Available until 11:59 pm on the day of the appointment.
   */
  private String downloadUrl;

  /**
   * PDF of the query report in Base64 (this field is only returned when the report is created)
   */
  private String reportFile;
}
