// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.models;

import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;

@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
public class RetrievePaymentBillingInformationOkResponse {

  /**
   * Payment data related to pix
   */
  private ApiPaymentPixQrCodeResponseDto pix;

  private ApiCreditCardTokenizeResponseDto creditCard;

  /**
   * Payment data related to bank slip
   */
  private ApiBankSlipBillingInfoResponseDto bankSlip;
}
