// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.ApiCheckoutSessionResponseDto;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class ApiCheckoutSessionResponseDtoValidator extends AbstractModelValidator<ApiCheckoutSessionResponseDto> {

  public ApiCheckoutSessionResponseDtoValidator(String fieldName) {
    super(fieldName);
  }

  public ApiCheckoutSessionResponseDtoValidator() {}

  @Override
  protected Violation[] validateModel(ApiCheckoutSessionResponseDto apiCheckoutSessionResponseDto) {
    return new ViolationAggregator()
      .add(
        new NumericValidator<Long>("minutesToExpire")
          .min(10L)
          .max(1440L)
          .optional()
          .validate(apiCheckoutSessionResponseDto.getMinutesToExpire())
      )
      .add(
        new ApiCheckoutSessionInstallmentDtoValidator("installment")
          .optional()
          .validate(apiCheckoutSessionResponseDto.getInstallment())
      )
      .aggregate();
  }
}
