// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.ApiCheckoutSessionInstallmentDto;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class ApiCheckoutSessionInstallmentDtoValidator
  extends AbstractModelValidator<ApiCheckoutSessionInstallmentDto> {

  public ApiCheckoutSessionInstallmentDtoValidator(String fieldName) {
    super(fieldName);
  }

  public ApiCheckoutSessionInstallmentDtoValidator() {}

  @Override
  protected Violation[] validateModel(ApiCheckoutSessionInstallmentDto apiCheckoutSessionInstallmentDto) {
    return new ViolationAggregator()
      .add(
        new NumericValidator<Long>("maxInstallmentCount")
          .min(1L)
          .max(21L)
          .optional()
          .validate(apiCheckoutSessionInstallmentDto.getMaxInstallmentCount())
      )
      .aggregate();
  }
}
