// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.ListSubaccountsParameters;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class ListSubaccountsParametersValidator extends AbstractModelValidator<ListSubaccountsParameters> {

  public ListSubaccountsParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListSubaccountsParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListSubaccountsParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
