// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.ListRecurrencesParameters;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class ListRecurrencesParametersValidator extends AbstractModelValidator<ListRecurrencesParameters> {

  public ListRecurrencesParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListRecurrencesParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListRecurrencesParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
