// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.ListCreditBureauReportsParameters;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class ListCreditBureauReportsParametersValidator
  extends AbstractModelValidator<ListCreditBureauReportsParameters> {

  public ListCreditBureauReportsParametersValidator(String fieldName) {
    super(fieldName);
  }

  public ListCreditBureauReportsParametersValidator() {}

  @Override
  protected Violation[] validateModel(ListCreditBureauReportsParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
