// This file was generated by liblab | https://liblab.com/

package com.asaas.apisdk.validation.validators.modelValidators;

import com.asaas.apisdk.models.RetrieveExtractParameters;
import com.asaas.apisdk.validation.Violation;
import com.asaas.apisdk.validation.ViolationAggregator;
import com.asaas.apisdk.validation.validators.NumericValidator;

public class RetrieveExtractParametersValidator extends AbstractModelValidator<RetrieveExtractParameters> {

  public RetrieveExtractParametersValidator(String fieldName) {
    super(fieldName);
  }

  public RetrieveExtractParametersValidator() {}

  @Override
  protected Violation[] validateModel(RetrieveExtractParameters requestParameters) {
    return new ViolationAggregator()
      .add(new NumericValidator<Long>("limit").max(100L).optional().validate(requestParameters.getLimit()))
      .aggregate();
  }
}
