// This file was generated by liblab | https://liblab.com/

package com.asaas.sdk.asaasjavasdk.config;

import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

@Builder
@Data
public class ApiKeyAuthConfig {

  @NonNull
  @Builder.Default
  private String apiKeyHeader = "access_token";

  private String apiKey;
}
